### ISSUE TITLE
添加好友时，点击agree，refuse无反应

### ISSUE THREAD

**Issue by itltf512116** [OpenIMSDK/Open-IM-Uniapp-Demo#1]
git clone代码，未更改API接口地址等配置信息，HBuilderX打包之后，两个账号添加好友，在new friends 列表中点击 agree,refuse按钮没反应，客户端也没有输出错误信息，请问这个是哪里问题呢？

**Comment by Bloomingg** [comment]
> git clone代码，未更改API接口地址等配置信息，HBuilderX打包之后，两个账号添加好友，在new friends 列表中点击 agree,refuse按钮没反应，客户端也没有输出错误信息，请问这个是哪里问题呢？

SDK修改了部分API参数格式，已更新代码，重新拉取打包调试即可。

**Comment by itltf512116** [comment]
更新之后，重新注册，点击netx step ,控制台输出
{ "data": { "errCode": 600, "errMsg": "User registration failed" }, "statusCode": 200, "header": { "Content-Type": "application/json", "Date": "Fri, 24 Sep 2021 05:35:57 GMT", "Connection": "keep-alive", "Server": "nginx/1.14.0 (Ubuntu)", "Access-Control-Max-Age": "172800", "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Methods": "*", "Access-Control-Allow-Headers": "*", "Access-Control-Allow-Credentials": "false", "Content-Length": "51", "Access-Control-Expose-Headers": "Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma,FooBar" }, "errMsg": "request:ok", "cookies": [] }

**Comment by Bloomingg** [comment]
> 更新之后，重新注册，点击netx step ,控制台输出
> { "data": { "errCode": 600, "errMsg": "User registration failed" }, "statusCode": 200, "header": { "Content-Type": "application/json", "Date": "Fri, 24 Sep 2021 05:35:57 GMT", "Connection": "keep-alive", "Server": "nginx/1.14.0 (Ubuntu)", "Access-Control-Max-Age": "172800", "Access-Control-Allow-Origin": "_", "Access-Control-Allow-Methods": "_", "Access-Control-Allow-Headers": "*", "Access-Control-Allow-Credentials": "false", "Content-Length": "51", "Access-Control-Expose-Headers": "Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma,FooBar" }, "errMsg": "request:ok", "cookies": [] }

目前在登录界面自定义输入一个账号，为未注册账号则会自动注册并登录。
