### ISSUE TITLE
是否可以出一个 npm 包作为客户端呢

### ISSUE THREAD

**Issue by tu6ge** [OpenIMSDK/Open-IM-Uniapp-Demo#10]
这样不仅可以用于 uniapp，还可以用于 web，其他框架的小程序， cordova，tauri 等使用场景

**Comment by tu6ge** [comment]
可以搞一个 npm 专属的开发文档吗，直接跳转到文档首页去，看的比较懵，我只想使用 npm 连接服务端，想尝试各种功能，比如加好友，上传图片，音频，获取离线消息等等，却无从下手

**Comment by Bloomingg** [comment]
有用于web的jssdk，参考文档：https://doc.rentsoft.cn/#/js_v2/sdk_integrate/development

**Comment by tu6ge** [comment]
好家伙，我都换工作了
