### ISSUE TITLE
Uniapp打包APP发送消息Web端接收不到

### ISSUE THREAD

**Issue by baboony** [OpenIMSDK/Open-IM-Uniapp-Demo#13]
我这边使用小程序发送消息给Web端没问题，正常接收/发送/拉取消息。当使用unaipp调用openIM.sendMessage接口时发送成功  但web端接收不到  
openIM.sendMessage(operationID, msgData, res.msg.recvID, "", offlinePushInfo, ({ data,errCode }) => {
	console.log(data);
	console.log(errCode);  //有时候才有返回0
})

我也下载您这边的Demo配置上我这边的服务器  能搜索出我这边的用户  但发送消息web端一样接收不到

**Comment by Bloomingg** [comment]
请体验新版本
