### ISSUE TITLE
uniapp项目的Android和ios本地插件项目没有开源吗？

### ISSUE THREAD

**Issue by xhb** [OpenIMSDK/Open-IM-Uniapp-Demo#14]
![截屏2022-07-23 14 15 16](https://user-images.githubusercontent.com/3167082/180593021-898d94e8-28f2-4bae-93c2-dc144a314e26.png)

这两个项目在哪里？？

**Comment by Jack-Chain** [comment]
https://github.com/OpenIMSDK/Open-IM-SDK-Uniapp

**Comment by xhb** [comment]
这个[Open-IM-SDK-Uniapp](https://github.com/OpenIMSDK/Open-IM-SDK-Uniapp) 是编译后的二进制文件，无法编译和修改，请推送对应的uniapp原生插件的项目，这样才能放心使用这个开源项目。。。
