### ISSUE TITLE
会话消息已读状态，无法清除

### ISSUE THREAD

**Issue by wzhsh90** [OpenIMSDK/Open-IM-Uniapp-Demo#24]
状态重置后，过段时间又出现。

一个消息会普通消息、撤回消息、系统通知

撤回消息与系统通知 不能通知api 将其状态修改为已读，导致未读数量一直存在。

测试方法：
1、安装查看会话
2、卸载重新安装，就会重现

**Comment by Bloomingg** [comment]
请体验新版本
