### ISSUE TITLE
Uniapp Packaging iOS Error

### ISSUE THREAD

**Issue by w1466818955** [openimsdk/open-im-uniapp-demo#29]
Undefined symbols for architecture arm64:
\"_Open_im_sdkSetGroupListener\", referenced from:
-[OpenIMModule setGroupListener] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSetConversationListener\", referenced from:
-[OpenIMModule setConversationListener] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSetAdvancedMsgListener\", referenced from:
-[OpenIMModule setAdvancedMsgListener] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSignalingGetTokenByRoomID\", referenced from:
-[OpenIMModule signalingGetTokenByRoomID:groupID:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSetOneConversationBurnDuration\", referenced from:
-[OpenIMModule setOneConversationBurnDuration:conversationID:burnDuration:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSearchGroupMembers\", referenced from:
-[OpenIMModule searchGroupMembers:searchOptions:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkNewRevokeMessage\", referenced from:
-[OpenIMModule newRevokeMessage:revokeMsg:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetGroupMemberListByJoinTimeFilter\", referenced from:
-[OpenIMModule getGroupMemberListByJoinTimeFilter:groupID:offset:count:joinTimeBegin:joinTimeEnd:filterUserIDList:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetWorkMomentsNotification\", referenced from:
-[OpenIMModule getWorkMomentsNotification:offset:count:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetDepartmentInfo\", referenced from:
-[OpenIMModule getDepartmentInfo:depID:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetDepartmentMemberAndSubDepartment\", referenced from:
-[OpenIMModule getDepartmentMemberAndSubDepartment:depID:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetUserInDepartment\", referenced from:
-[OpenIMModule getUserInDepartment:userID:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetDepartmentMember\", referenced from:
-[OpenIMModule getDepartmentMember:depID:offset:count:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSetAppBackgroundStatus\", referenced from:
-[OpenIMModule setAppBackgroundStatus:isBackground:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSignalingHungUp\", referenced from:
-[OpenIMModule signalingHungUp:options:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSignalingReject\", referenced from:
-[OpenIMModule signalingReject:options:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSignalingAccept\", referenced from:
-[OpenIMModule signalingAccept:options:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSignalingInviteInGroup\", referenced from:
-[OpenIMModule signalingInviteInGroup:options:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkResetConversationGroupAtType\", referenced from:
-[OpenIMModule resetConversationGroupAtType:conversationID:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSetGlobalRecvMessageOpt\", referenced from:
-[OpenIMModule setGlobalRecvMessageOpt:opt:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSignalingCancel\", referenced from:
-[OpenIMModule signalingCancel:options:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSetGroupVerification\", referenced from:
-[OpenIMModule setGroupVerification:groupID:verification:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSetGroupMemberRoleLevel\", referenced from:
-[OpenIMModule setGroupMemberRoleLevel:groupID:userID:roleLevel:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSearchGroups\", referenced from:
-[OpenIMModule searchGroups:options:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkClearWorkMomentsNotification\", referenced from:
-[OpenIMModule clearWorkMomentsNotification:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSearchFriends\", referenced from:
-[OpenIMModule searchFriends:options:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkAcceptGroupApplication\", referenced from:
-[OpenIMModule acceptGroupApplication:groupID:fromUserID:handleMsg:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkJoinGroup\", referenced from:
-[OpenIMModule joinGroup:groupID:reqMsg:joinSource:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetJoinedGroupList\", referenced from:
-[OpenIMModule getJoinedGroupList:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkCreateLocationMessage\", referenced from:
-[OpenIMModule createLocationMessage:desc:latitude:longitude:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetGroupMemberList\", referenced from:
-[OpenIMModule getGroupMemberList:groupID:filter:offset:count:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetGroupMembersInfo\", referenced from:
-[OpenIMModule getGroupMembersInfo:groupID:userIDList:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkKickGroupMember\", referenced from:
-[OpenIMModule kickGroupMember:groupID:reason:userIDList:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkCreateCustomMessage\", referenced from:
-[OpenIMModule createCustomMessage:data:expand:desc:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetConversationListSplit\", referenced from:
-[OpenIMModule getConversationListSplit:offset:count:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetConversationRecvMessageOpt\", referenced from:
-[OpenIMModule getConversationRecvMessageOpt:conversationIDList:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSearchLocalMessages\", referenced from:
-[OpenIMModule searchLocalMessages:searchParam:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkInsertSingleMessageToLocalStorage\", referenced from:
-[OpenIMModule insertSingleMessageToLocalStorage:message:recvID:sendID:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSetOneConversationPrivateChat\", referenced from:
-[OpenIMModule setOneConversationPrivateChat:conversationID:isPrivate:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetTotalUnreadMsgCount\", referenced from:
-[OpenIMModule getTotalUnreadMsgCount:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSetFriendRemark\", referenced from:
-[OpenIMModule setFriendRemark:userIDRemark:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetBlackList\", referenced from:
-[OpenIMModule getBlackList:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkPinConversation\", referenced from:
-[OpenIMModule pinConversation:conversationID:isPinned:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkCreateSoundMessageFromFullPath\", referenced from:
-[OpenIMModule createSoundMessageFromFullPath:soundPath:duration:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkDeleteAllConversationFromLocal\", referenced from:
-[OpenIMModule deleteAllConversationFromLocal:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkDeleteConversationFromLocalAndSvr\", referenced from:
-[OpenIMModule deleteConversationFromLocalAndSvr:conversationID:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkDeleteConversation\", referenced from:
-[OpenIMModule deleteConversation:conversationID:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetUsersInfo\", referenced from:
-[OpenIMModule getUsersInfo:userIDList:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetGroupsInfo\", referenced from:
-[OpenIMModule getGroupsInfo:groupIDList:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetWorkMomentsUnReadCount\", referenced from:
-[OpenIMModule getWorkMomentsUnReadCount:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetAllConversationList\", referenced from:
-[OpenIMModule getAllConversationList:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkClearGroupHistoryMessageFromLocalAndSvr\", referenced from:
-[OpenIMModule clearGroupHistoryMessageFromLocalAndSvr:groupID:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkClearGroupHistoryMessage\", referenced from:
-[OpenIMModule clearGroupHistoryMessage:groupID:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkDeleteMessageFromLocalStorage\", referenced from:
-[OpenIMModule deleteMessageFromLocalStorage:message:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSetGroupMemberNickname\", referenced from:
-[OpenIMModule setGroupMemberNickname:groupID:userID:groupMemberNickname:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkClearC2CHistoryMessage\", referenced from:
-[OpenIMModule clearC2CHistoryMessage:userID:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkInsertGroupMessageToLocalStorage\", referenced from:
-[OpenIMModule insertGroupMessageToLocalStorage:message:groupID:sendID:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkDismissGroup\", referenced from:
-[OpenIMModule dismissGroup:groupID:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSignalingInvite\", referenced from:
-[OpenIMModule signalingInvite:options:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetDesignatedFriendsInfo\", referenced from:
-[OpenIMModule getDesignatedFriendsInfo:userIDList:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkDeleteMessageFromLocalAndSvr\", referenced from:
-[OpenIMModule deleteMessageFromLocalAndSvr:message:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSetFriendListener\", referenced from:
-[OpenIMModule setFriendListener] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetSelfUserInfo\", referenced from:
-[OpenIMModule getSelfUserInfo:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkChangeGroupMemberMute\", referenced from:
-[OpenIMModule changeGroupMemberMute:groupID:userID:mutedSeconds:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkDeleteAllMsgFromLocal\", referenced from:
-[OpenIMModule deleteAllMsgFromLocal:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkQuitGroup\", referenced from:
-[OpenIMModule quitGroup:groupID:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkTypingStatusUpdate\", referenced from:
-[OpenIMModule typingStatusUpdate:recvID:msgTip:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetRecvGroupApplicationList\", referenced from:
-[OpenIMModule getRecvGroupApplicationList:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkMarkGroupMessageAsRead\", referenced from:
-[OpenIMModule markGroupMessageAsRead:groupID:msgIDList:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSetSignalingListener\", referenced from:
-[OpenIMModule initSDK:config:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkRevokeMessage\", referenced from:
-[OpenIMModule revokeMessage:message:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetHistoryMessageList\", referenced from:
-[OpenIMModule getHistoryMessageList:messageOptions:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkCreateGroup\", referenced from:
-[OpenIMModule createGroup:groupBaseInfo:memberList:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSendMessageNotOss\", referenced from:
-[OpenIMModule sendMessageNotOss:message:recvID:groupID:offlinePushInfo:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkLogin\", referenced from:
-[OpenIMModule login:userId:token:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetRecvFriendApplicationList\", referenced from:
-[OpenIMModule getRecvFriendApplicationList:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSendMessage\", referenced from:
-[OpenIMModule sendMessage:message:recvID:groupID:offlinePushInfo:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkCreateCardMessage\", referenced from:
-[OpenIMModule createCardMessage:cardDesc:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkCreateAdvancedQuoteMessage\", referenced from:
-[OpenIMModule createAdvancedQuoteMessage:text:message:messageEntityList:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkAddBlack\", referenced from:
-[OpenIMModule addBlack:blackUserID:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkCreateImageMessageByURL\", referenced from:
-[OpenIMModule createImageMessageByURL:sourcePicture:bigPicture:snapshotPicture:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkCreateFileMessageFromFullPath\", referenced from:
-[OpenIMModule createFileMessageFromFullPath:filePath:fileName:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSdkVersion\", referenced from:
-[OpenIMModule getSdkVersion] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkCreateFileMessage\", referenced from:
-[OpenIMModule createFileMessage:filePath:fileName:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkCreateVideoMessage\", referenced from:
-[OpenIMModule createVideoMessage:videoPath:videoType:duration:snapshotPath:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSearchOrganization\", referenced from:
-[OpenIMModule searchOrganization:options:offset:count:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkCreateSoundMessageByURL\", referenced from:
-[OpenIMModule createSoundMessageByURL:soundInfo:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkCreateImageMessage\", referenced from:
-[OpenIMModule createImageMessage:imagePath:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetOneConversation\", referenced from:
-[OpenIMModule getOneConversation:sessionType:sourceID:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetMultipleConversation\", referenced from:
-[OpenIMModule getMultipleConversation:conversationIDList:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkCreateSoundMessage\", referenced from:
-[OpenIMModule createSoundMessage:soundPath:duration:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkCreateTextAtMessage\", referenced from:
-[OpenIMModule createTextAtMessage:textMsg:atUserIDList:atUserInfoList:message:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkAddFriend\", referenced from:
-[OpenIMModule addFriend:userIDReqMsg:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkAcceptFriendApplication\", referenced from:
-[OpenIMModule acceptFriendApplication:userIDHandleMsg:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkRemoveBlack\", referenced from:
-[OpenIMModule removeBlack:removeUserID:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSetAppBadge\", referenced from:
-[OpenIMModule setAppBadge:appUnreadCount:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkClearC2CHistoryMessageFromLocalAndSvr\", referenced from:
-[OpenIMModule clearC2CHistoryMessageFromLocalAndSvr:userID:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetSubDepartment\", referenced from:
-[OpenIMModule getSubDepartment:depID:offset:count:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkRefuseGroupApplication\", referenced from:
-[OpenIMModule refuseGroupApplication:groupID:fromUserID:handleMsg:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkCreateVideoMessageFromFullPath\", referenced from:
-[OpenIMModule createVideoMessageFromFullPath:videoPath:videoType:duration:snapshotPath:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkDeleteFriend\", referenced from:
-[OpenIMModule deleteFriend:friendUserID:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSetSelfInfo\", referenced from:
-[OpenIMModule setSelfInfo:userInfo:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkCreateImageMessageFromFullPath\", referenced from:
-[OpenIMModule createImageMessageFromFullPath:imagePath:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkInitSDK\", referenced from:
-[OpenIMModule initSDK:config:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkUploadFile\", referenced from:
-[OpenIMModule uploadFile:filePath:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkTransferGroupOwner\", referenced from:
-[OpenIMModule transferGroupOwner:groupID:newOwnerUserID:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSetGroupApplyMemberFriend\", referenced from:
-[OpenIMModule setGroupApplyMemberFriend:groupID:rule:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkCreateTextMessage\", referenced from:
-[OpenIMModule createTextMessage:textMsg:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkChangeGroupMute\", referenced from:
-[OpenIMModule changeGroupMute:groupID:isMute:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkCreateForwardMessage\", referenced from:
-[OpenIMModule createForwardMessage:message:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSetOrganizationListener\", referenced from:
-[OpenIMModule initSDK:config:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkMarkMessageAsReadByConID\", referenced from:
-[OpenIMModule markMessageAsReadByConID:conversationID:msgIDList:callback:] in OpenIMUniPlugin(OpenIMModule.o)
-[OpenIMModule markConversationHasRead:conversationID:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetAdvancedHistoryMessageList\", referenced from:
-[OpenIMModule getAdvancedHistoryMessageList:messageOptions:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkMarkGroupMessageHasRead\", referenced from:
-[OpenIMModule markGroupMessageHasRead:groupID:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkDeleteAllMsgFromLocalAndSvr\", referenced from:
-[OpenIMModule deleteAllMsgFromLocalAndSvr:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetLoginUser\", referenced from:
-[OpenIMModule getLoginUser] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkInviteUserToGroup\", referenced from:
-[OpenIMModule inviteUserToGroup:groupID:reason:userIDList:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSignalingGetRoomByGroupID\", referenced from:
-[OpenIMModule signalingGetRoomByGroupID:groupID:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetSendFriendApplicationList\", referenced from:
-[OpenIMModule getSendFriendApplicationList:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSetGroupInfo\", referenced from:
-[OpenIMModule setGroupInfo:groupID:groupInfo:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSetGroupLookMemberInfo\", referenced from:
-[OpenIMModule setGroupLookMemberInfo:groupID:rule:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkRefuseFriendApplication\", referenced from:
-[OpenIMModule refuseFriendApplication:userIDHandleMsg:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkCreateQuoteMessage\", referenced from:
-[OpenIMModule createQuoteMessage:text:message:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkWakeUp\", referenced from:
-[OpenIMModule wakeUp:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSetConversationRecvMessageOpt\", referenced from:
-[OpenIMModule setConversationRecvMessageOpt:conversationIDList:opt:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetLoginStatus\", referenced from:
-[OpenIMModule getLoginStatus] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSetBatchMsgListener\", referenced from:
-[OpenIMModule setBatchMsgListener] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetSendGroupApplicationList\", referenced from:
-[OpenIMModule getSendGroupApplicationList:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkCreateMergerMessage\", referenced from:
-[OpenIMModule createMergerMessage:messageList:title:summaryList:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSetOneConversationRecvMessageOpt\", referenced from:
-[OpenIMModule setOneConversationRecvMessageOpt:conversationID:opt:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkCreateVideoMessageByURL\", referenced from:
-[OpenIMModule createVideoMessageByURL:videoInfo:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkCheckFriend\", referenced from:
-[OpenIMModule checkFriend:userIdList:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkMarkC2CMessageAsRead\", referenced from:
-[OpenIMModule markC2CMessageAsRead:userID:msgIDList:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkCreateFileMessageByURL\", referenced from:
-[OpenIMModule createFileMessageByURL:fileInfo:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSetUserListener\", referenced from:
-[OpenIMModule setUserListener] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkLogout\", referenced from:
-[OpenIMModule logout:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkGetFriendList\", referenced from:
-[OpenIMModule getFriendList:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSetConversationDraft\", referenced from:
-[OpenIMModule setConversationDraft:conversationID:draftText:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkSetWorkMomentsListener\", referenced from:
-[OpenIMModule initSDK:config:] in OpenIMUniPlugin(OpenIMModule.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Bloomingg** [comment]
请使用云端插件打包
