### ISSUE TITLE
第一次注册设置用户信息和头像时一直loading

### ISSUE THREAD

**Issue by lyl-code** [OpenIMSDK/Open-IM-Uniapp-Demo#3]
在注册流程中跑到设置用户信息和头像的时候执行了importRelationShip-》appServerLogin方法，但是接口返回密码不正确，看了服务端接口源码需要一个传密码参数，但是示例中是没有传密码参数的，如下图：
![image](https://user-images.githubusercontent.com/84664675/143037874-25cda475-8ebc-4f35-a45b-dc5aaf1f5728.png)

![image](https://user-images.githubusercontent.com/84664675/143037738-b97692e6-8124-4172-952f-b368cb005e66.png)

**Comment by lyl-code** [comment]
补充下，是login/setInfo页面执行的importRelationShip方法

**Comment by Bloomingg** [comment]
> 在注册流程中跑到设置用户信息和头像的时候执行了importRelationShip-》appServerLogin方法，但是接口返回密码不正确，看了服务端接口源码需要一个传密码参数，但是示例中是没有传密码参数的，如下图： ![image](https://user-images.githubusercontent.com/84664675/143037874-25cda475-8ebc-4f35-a45b-dc5aaf1f5728.png)
> 
> ![image](https://user-images.githubusercontent.com/84664675/143037738-b97692e6-8124-4172-952f-b368cb005e66.png)

你好，这个方法是不需要密码的，因为这里是直接访问IM Server的后台管理接口，获取管理员token->导入好友->导入群聊。是为了demo体验用户在注册时导入默认的好友和群聊，方便交流与体验。你自己部署的服务端上是没有这几个用户与群聊的，注释即可。具体可查看文档说明：https://doc.rentsoft.cn/server_doc/admin.html

**Comment by lyl-code** [comment]
> > 在注册流程中跑到设置用户信息和头像的时候执行了importRelationShip-》appServerLogin方法，但是接口返回密码不正确，看了服务端接口源码需要一个传密码参数，但是示例中是没有传密码参数的，如下图： ![image](https://user-images.githubusercontent.com/84664675/143037874-25cda475-8ebc-4f35-a45b-dc5aaf1f5728.png)
> > ![image](https://user-images.githubusercontent.com/84664675/143037738-b97692e6-8124-4172-952f-b368cb005e66.png)
> 
> 你好，这个方法是不需要密码的，因为这里是直接访问IM Server的后台管理接口，获取管理员token->导入好友->导入群聊。是为了demo体验用户在注册时导入默认的好友和群聊，方便交流与体验。你自己部署的服务端上是没有这几个用户与群聊的，注释即可。具体可查看文档说明：https://doc.rentsoft.cn/server_doc/admin.html

谢谢解答，我目前的方案也是把那段导入群聊的给注释了
