### ISSUE TITLE
Configure push, send message without push

### ISSUE THREAD

**Issue by fulus06** [openimsdk/open-im-uniapp-demo#30]
部署教程： https://doc.rentsoft.cn/#/v2/server_deploy/easy_deploy_new

uniapp配置个推（使用uniPush1.0， unipush2被封装了没有MasterSecret）信息，使用Java demo可以推送成功
![image](https://user-images.githubusercontent.com/12890684/230759993-0cfbf839-e488-4f2f-a5f6-1987528efaf0.png)
(图1：uniapp push 配置)

![image](https://user-images.githubusercontent.com/12890684/230759919-b218b1d3-9e9b-4cae-85e8-ce204ab41825.png)
(图2: uniapp 个推参数)

im server配置：config/usualConfig.yaml
![image](https://user-images.githubusercontent.com/12890684/230759950-71b997b0-ec2d-4695-be54-2501d0c61214.png)
（图3：服务端个推配置信息）

问题：
好友间发送消息没有推送信息。
自己写Java demo，使用图2的配置验证，可以推送到手机（open-im-uniapp-demo）。

**Comment by Bloomingg** [comment]
APP切到后台运行时调用如下方法，服务端才会进行推送
`IMSDK.compatibleAPI(IMSDK.IMMethods.SetAppBackgroundStatus, IMSDK.uuidv4(), true)`
同样切换到前台时设置为false

**Comment by lgz5689** [comment]
目前已经更新到3.0版本，参考demo实现，https://github.com/OpenIMSDK/Open-IM-Uniapp-Demo
