### ISSUE TITLE
Unable to send images using Alibaba Cloud OSS

### ISSUE THREAD

**Issue by fulus06** [openimsdk/open-im-uniapp-demo#31]
部署教程: https://doc.rentsoft.cn/#/v2/server_deploy/easy_deploy_new

im server配置：docker-compose_cfg/config.yaml

![image](https://user-images.githubusercontent.com/12890684/230760122-804e0e15-4831-4bb6-b144-dbf1cc140420.png)

客户端配置如下：
![image](https://user-images.githubusercontent.com/12890684/230760143-a2980c0b-3dce-4677-b47a-71b0abe6538d.png)

错误信息：
![image](https://user-images.githubusercontent.com/12890684/230760161-e6e17901-3b69-4eda-82a1-4259d7cae14b.png)

问题：
如上图，host为空

**Comment by lgz5689** [comment]
目前已经更新到3.x版本，可以查看3.x的官方文档
