### ISSUE TITLE
Bug: Why can't the QR code and business card enter at all

### ISSUE THREAD

**Issue by jg-8** [openimsdk/open-im-uniapp-demo#37]
### What happened?

uniapp android 安卓后，二维码名片怎么点都进不去

### What did you expect to happen?

能够进入看到二维码，扫码可以添加用户

### How can we reproduce it (as minimally and precisely as possible)?

单击、双击，二维码名片的任何位置都进不去。

### version

最新版本
branch: main

last commit:

commit 3f744ba57eae66f14ae72be9dbf0a564536a8237 (HEAD -> main, origin/main, origin/HEAD)
Author: skiffer-git <72860476+skiffer-git@users.noreply.github.com>
Date:   Tue Aug 22 18:40:03 2023 +0800

    Update Readme.md

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by lgz5689** [comment]
目前已经更新到3.0版本，参考demo实现，https://github.com/OpenIMSDK/Open-IM-Uniapp-Demo
