### ISSUE TITLE
Feature: The send message window only has the send image button. Can I add the send file button function？

### ISSUE THREAD

**Issue by jg-8** [openimsdk/open-im-uniapp-demo#38]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [OpenIMSDK Slack](https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg) and got positive feedback

### Is this feature request related to a problem?

None

### Problem Description

只能发送图片，不能发送文件

### Solution Description

增加一个类似发送文件的功能按钮，类似发送图片

### Benefits

发送文件根发送图片是一样，都是普适性功能，谢谢

**Comment by Bloomingg** [comment]
这个只是demo，对应功能可以自行开发
