### ISSUE TITLE
After sending images on the mobile phone, there is no local cache for the images, and every time you open it, you need to download the images again

### ISSUE THREAD

**Issue by jg-8** [openimsdk/open-im-uniapp-demo#39]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [OpenIMSDK Slack](https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg) and got positive feedback

### Is this feature request related to a problem?

None

### Problem Description

聊天窗口，每次进入，都得重新下载图片，这个看着是比较影响性能的，建议能够做本地化缓存。

### Solution Description

能够做聊天记录的本地化。缓存，缓存图片、文件

### Benefits

本地化缓存可以节省服务器的开销。

**Comment by Bloomingg** [comment]
这个只是demo，对应功能可以自行开发
