### ISSUE TITLE
Bug: Message forwarding flashback

### ISSUE THREAD

**Issue by yoyoyo-wzw** [openimsdk/open-im-uniapp-demo#40]
### What happened?

转发消息调用的是IMMethods.CreateForwardMessage api，在ios端一触发这个api，整个应用会闪退关闭，而且这个问题是必现的，测试了三个ios了，都有这个问题

### What did you expect to happen?

ios端正常生成转发消息

### How can we reproduce it (as minimally and precisely as possible)?

IMSDK.asyncApi(IMMethods.CreateForwardMessage, IMSDK.uuid(), this.message)

### version

openim-uniapp-polyfill  1.0.5

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by Bloomingg** [comment]
3.3.0版本已修复
