### ISSUE TITLE
Bug: TypeError: undefined is not an object (evaluating 'F[e]')

### ISSUE THREAD

**Issue by lakerchen** [openimsdk/open-im-uniapp-demo#41]
### What happened?

在HBuilderX中，点击“运行-运行到手机或模拟器-运行到iOS模拟器App基座”，控制台有如下报错：

```
13:40:31.655 正在差量编译...
13:40:32.820 项目 'open-im-uniapp-demo' 编译成功。
13:40:32.832 正在同步手机端程序文件...
13:40:32.883 同步手机端程序文件完成
13:40:35.152 [JS Framework] 当前运行的基座不包含原生插件[Tuoyun-OpenIMSDK]，请在manifest中配置该插件，重新制作包括该原生插件的自定义运行基座 __WARN
13:40:35.153 [JS Framework] 当前运行的基座不包含原生插件[Tuoyun-OpenIMSDK-OUIFilePicker]，请在manifest中配置该插件，重新制作包括该原生插件的自定义运行基座 __WARN
13:40:35.153 
13:40:35.153 %c uView V2.0.34 %c https://uviewui.com/
13:40:35.153 ,  color: #ffffff; background: #3c9cff; padding:5px 0; border-radius: 5px; at uni_modules/uview-ui/libs/config/config.js:6
13:40:35.153 setGlobalIMlistener at App.vue:64
13:40:35.153 get dir failed 111 at App.vue:440
13:40:35.154 TypeError: undefined is not an object (evaluating 'F[e]') at App.vue:441
13:40:35.154 [Object] {"config":{}}  at store/modules/user.js:96
```

点击登录按钮，一直在loading：

<img width="453" alt="image" src="https://github.com/openimsdk/open-im-uniapp-demo/assets/3245703/af6296c4-b8e8-4f51-9e6e-2e339be77921">

### What did you expect to happen?

登录成功

### How can we reproduce it (as minimally and precisely as possible)?

将git项目clone下来，修改common/config.js中的服务器地址，点击“运行-运行到手机或模拟器-运行到iOS模拟器App基座”

### version

HBuilderX：3.8.12.20230817

### Cloud provider

无

### OS version

Apple M1 Pro，macOS 13.5

### Install tools

<details>
</details>

**Comment by Bloomingg** [comment]
1.参考readme云打包自定义基座,以基座运行。
2.ios运行到真机
