### ISSUE TITLE
Bug: Component introduction error

### ISSUE THREAD

**Issue by xxlxh** [openimsdk/open-im-uniapp-demo#42]
### What happened?

![image](https://github.com/openimsdk/open-im-uniapp-demo/assets/141909328/2597923f-1678-4ce3-bdac-cd06e97a2abc)

### What did you expect to happen?

这个是组件引入报错 不确定是否有影响 在app会报错  h5不会  

### How can we reproduce it (as minimally and precisely as possible)?

这个是组件引入报错 不确定是否有影响 在app会报错  h5不会  

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by lgz5689** [comment]
这个错误并不影响运行，可以忽略
