### ISSUE TITLE
Bug: After checking historical messages during chat, I found that the latest message was that long pressing on the text in chat did not bring up the menu

### ISSUE THREAD

**Issue by xxlxh** [openimsdk/open-im-uniapp-demo#43]
### What did you expect to happen?

![image](https://github.com/openimsdk/open-im-uniapp-demo/assets/141909328/8866ce7e-2b1e-4369-b4ba-62a33dcccda3)

### How can we reproduce it (as minimally and precisely as possible)?

聊天查看历史消息后 最新消息发现聊天长按文本 弹不出菜单    历史的部分可以

### Anything else we need to know?

![image](https://github.com/openimsdk/open-im-uniapp-demo/assets/141909328/dae132be-f7ef-4644-b13a-dc5fa65feeda)

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by lgz5689** [comment]
菜单功能需要自行实现，最新的3.xdemo中已经不包括长按弹出菜单了
