### ISSUE TITLE
Bug: Uni-App群移除成员无法使用,基座调试很多错误

### ISSUE THREAD

**Issue by jujianan112233** [openimsdk/open-im-uniapp-demo#47]
### What happened?

Bug: Uni-App群移除成员无法使用,基座调试很多错误

### What did you expect to happen?

Bug: Uni-App群移除成员无法使用,基座调试很多错误

### How can we reproduce it (as minimally and precisely as possible)?

Bug: Uni-App群移除成员无法使用,基座调试很多错误

### version

 HBuilderX：3.7.11.20230427

### Cloud provider

无

**Comment by lgz5689** [comment]
可以提供下基座调试内的错误日志
