### ISSUE TITLE
登录跟系统同步极慢，甚至第一次都失败，关掉 app 重开，第二次基本就可以正常

### ISSUE THREAD

**Issue by jg-8** [openimsdk/open-im-uniapp-demo#48]
### What happened?

有时候，经常第一次打开 app 的时候，进行登录，登录按钮就一直转圈圈，没有跳转，关掉再打开登录就可以登录进去。
进入后，同步有时候也一直在同步中，关掉重开就可以正常同步。

### What did you expect to happen?

一次性快速登录，登录后同步中，也一次性快速完成

### How can we reproduce it (as minimally and precisely as possible)?

多人反馈

### version

v3 最新版

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by lgz5689** [comment]
同步消息是会去服务端拉取消息到本地，如果数据量大，确实是会消耗一定的时间

**Comment by skiffer-git** [comment]
用户大概有多少个会话？

**Comment by jg-8** [comment]
> 用户大概有多少个会话？

大概也就是3-4，群里面也没几条消息记录
