### ISSUE TITLE
demo下载打包ios，选择云插件，提示错误

### ISSUE THREAD

**Issue by jujianan112233** [openimsdk/open-im-uniapp-demo#49]
### What did you expect to happen?

ld: warning: object file ([UniPluginPath]Tuoyun-OpenIMSDK/ios//OpenIMCore.framework/OpenIMCore(000039.o)) was built for newer iOS version (13.0) than being linked (9.0)
Undefined symbols for architecture arm64:
\"_Open_im_sdkDeleteAllConversationFromLocal\", referenced from:
-[OpenIMModule deleteAllConversationFromLocal:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkDeleteConversationFromLocal\", referenced from:
-[OpenIMModule deleteConversationFromLocal:conversationID:callback:] in OpenIMUniPlugin(OpenIMModule.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
{ platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00008112-001150CA3EC3C01E }
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:iOS Simulator, id:5BD30D75-25D3-4BC8-A4D2-EE955F15524D, OS:16.2, name:iPad (10th generation) }
{ platform:iOS Simulator, id:037D3741-E972-4441-BBC2-E1E98B5388AF, OS:16.2, name:iPad Air (5th generation) }
{ platform:iOS Simulator, id:E60C95B7-F98A-4B32-82B2-C6A47CF43036, OS:16.2, name:iPad Pro (11-inch) (4th generation) }
{ platform:iOS Simulator, id:4097C857-B917-4695-9F42-61AB950CE827, OS:16.2, name:iPad Pro (12.9-inch) (6th generation) }
{ platform:iOS Simulator, id:6E9ABFA9-5123-49AE-A702-65E35AB75E4E, OS:16.2, name:iPad mini (6th generation) }
{ platform:iOS Simulator, id:1F110B45-0CA7-4275-BDE0-7B438309C47E, OS:16.2, name:iPhone 14 }
{ platform:iOS Simulator, id:F09AA35A-066D-46F0-8F03-F90C12699F4A, OS:16.2, name:iPhone 14 Plus }
{ platform:iOS Simulator, id:434FCFDB-034F-4556-97EA-569DE189172D, OS:16.2, name:iPhone 14 Pro }
{ platform:iOS Simulator, id:3E399DFD-1047-42B4-87CB-57ED905BAC73, OS:16.2, name:iPhone 14 Pro Max }
{ platform:iOS Simulator, id:86EB4296-D923-4EBC-8C02-3378D03C9119, OS:16.2, name:iPhone SE (3rd generation) }
** ARCHIVE FAILED **The following build commands failed:
Ld /Users/[Name]/Library/Developer/Xcode/DerivedData/HBuilder-cqyprtcdslmyvogcscxmrfhirgkg/Build/Intermediates.noindex/ArchiveIntermediates/HBuilder/InstallationBuildProductsLocation/Applications/HBuilder.app/HBuilder normal (in target 'HBuilder' from project 'HBuilder')
(1 failure)

### How can we reproduce it (as minimally and precisely as possible)?

ld: warning: object file ([UniPluginPath]Tuoyun-OpenIMSDK/ios//OpenIMCore.framework/OpenIMCore(000039.o)) was built for newer iOS version (13.0) than being linked (9.0)
Undefined symbols for architecture arm64:
\"_Open_im_sdkDeleteAllConversationFromLocal\", referenced from:
-[OpenIMModule deleteAllConversationFromLocal:callback:] in OpenIMUniPlugin(OpenIMModule.o)
\"_Open_im_sdkDeleteConversationFromLocal\", referenced from:
-[OpenIMModule deleteConversationFromLocal:conversationID:callback:] in OpenIMUniPlugin(OpenIMModule.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
{ platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00008112-001150CA3EC3C01E }
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:iOS Simulator, id:5BD30D75-25D3-4BC8-A4D2-EE955F15524D, OS:16.2, name:iPad (10th generation) }
{ platform:iOS Simulator, id:037D3741-E972-4441-BBC2-E1E98B5388AF, OS:16.2, name:iPad Air (5th generation) }
{ platform:iOS Simulator, id:E60C95B7-F98A-4B32-82B2-C6A47CF43036, OS:16.2, name:iPad Pro (11-inch) (4th generation) }
{ platform:iOS Simulator, id:4097C857-B917-4695-9F42-61AB950CE827, OS:16.2, name:iPad Pro (12.9-inch) (6th generation) }
{ platform:iOS Simulator, id:6E9ABFA9-5123-49AE-A702-65E35AB75E4E, OS:16.2, name:iPad mini (6th generation) }
{ platform:iOS Simulator, id:1F110B45-0CA7-4275-BDE0-7B438309C47E, OS:16.2, name:iPhone 14 }
{ platform:iOS Simulator, id:F09AA35A-066D-46F0-8F03-F90C12699F4A, OS:16.2, name:iPhone 14 Plus }
{ platform:iOS Simulator, id:434FCFDB-034F-4556-97EA-569DE189172D, OS:16.2, name:iPhone 14 Pro }
{ platform:iOS Simulator, id:3E399DFD-1047-42B4-87CB-57ED905BAC73, OS:16.2, name:iPhone 14 Pro Max }
{ platform:iOS Simulator, id:86EB4296-D923-4EBC-8C02-3378D03C9119, OS:16.2, name:iPhone SE (3rd generation) }
** ARCHIVE FAILED **The following build commands failed:
Ld /Users/[Name]/Library/Developer/Xcode/DerivedData/HBuilder-cqyprtcdslmyvogcscxmrfhirgkg/Build/Intermediates.noindex/ArchiveIntermediates/HBuilder/InstallationBuildProductsLocation/Applications/HBuilder.app/HBuilder normal (in target 'HBuilder' from project 'HBuilder')
(1 failure)

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by jujianan112233** [comment]
@Bloomingg  大佬有空帮忙看看

**Comment by Bloomingg** [comment]
> @Bloomingg 大佬有空帮忙看看

用3.4.0.1
