### ISSUE TITLE
安卓本地打的包登录报错

### ISSUE THREAD

**Issue by chen459236681** [openimsdk/open-im-uniapp-demo#50]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [OpenIMSDK Slack](https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg) and got positive feedback

### Is this feature request related to a problem?

None

### Problem Description

在HBX云打的包登录没有问题，安卓本地打的包登录提示操作失败，
密码错误会有正确提示，密码正确提示操作失败，
本地包是否要配置其他什么东西sdk啥的，到底是sdk问题还是接口问题。

### Solution Description

1

### Benefits

1

### Potential Drawbacks

1

### Additional Information

1

**Comment by lgz5689** [comment]
不要用本地打包，要使用云打包。

**Comment by chen459236681** [comment]
> 不要用本地打包，要使用云打包。

为什么。云打包太慢还有次数限制。本地打包是有啥问题没处理好吗。上次群里有个人好像能本地打包！

**Comment by lgz5689** [comment]
> > 不要用本地打包，要使用云打包。
> 
> 为什么。云打包太慢还有次数限制。本地打包是有啥问题没处理好吗。上次群里有个人好像能本地打包！

你使用了云插件 只能云打包 用本地插件才可以本地打包，而且一般发布的时候才需要打包，开发的时候使用自定义基座就可以了

**Comment by chen459236681** [comment]
> > > 不要用本地打包，要使用云打包。
> > 
> > 
> > 为什么。云打包太慢还有次数限制。本地打包是有啥问题没处理好吗。上次群里有个人好像能本地打包！
> 
> 你使用了云插件 只能云打包 用本地插件才可以本地打包，而且一般发布的时候才需要打包，开发的时候使用自定义基座就可以了

我也使用过本地插件本地打包，还是不行的。主要是打包给别的手机测，不能一直用云打包，本地快，早发现问题早解决，要是发布才遇上就GG了。不知道使用本地插件，本地打包需要注意什么，配置些什么。反正我能运行，登录报错！

**Comment by lgz5689** [comment]
发一下详细的报错信息

**Comment by chen459236681** [comment]
> 发一下详细的报错信息

![image](https://github.com/openimsdk/open-im-uniapp-demo/assets/35327293/25cacc07-2a51-481a-a37a-aeaeb7a362da)
![image](https://github.com/openimsdk/open-im-uniapp-demo/assets/35327293/0c4944ef-f686-4352-87f1-2030287cc47a)
图一弹窗空白。其他错误信息不知道怎么测了

**Comment by lgz5689** [comment]
把 try 的内容也发出来 ，可以顺便打印 IMSDK.nomalApi 看下有没有内容。

**Comment by lgz5689** [comment]
这个弹窗 checkLoginError 只是用来处理 Chat 的错误，IM 的错误，直接把内容输出出来。

**Comment by chen459236681** [comment]
> 这个弹窗 checkLoginError 只是用来处理 Chat 的错误，IM 的错误，直接把内容输出出来。

uni.showModal({
	title: '看看SDK',
	content: IMSDK.nomalApi,
	success:(res)=> {
		if (res.confirm) {
			console.log('用户点击确定');
		} else if (res.cancel) {
			console.log('用户点击取消');
		}
	}
});

显示空白

**Comment by chen459236681** [comment]
> > 这个弹窗 checkLoginError 只是用来处理 Chat 的错误，IM 的错误，直接把内容输出出来。
> 
> uni.showModal({ title: '看看SDK', content: IMSDK.nomalApi, success:(res)=> { if (res.confirm) { console.log('用户点击确定'); } else if (res.cancel) { console.log('用户点击取消'); } } });
> 
> 显示空白

![image](https://github.com/openimsdk/open-im-uniapp-demo/assets/35327293/9ad3d6bf-113c-41d7-b01d-662dd48b01e1)
![image](https://github.com/openimsdk/open-im-uniapp-demo/assets/35327293/594b0503-5fb9-4046-adde-516afe611e91)
![e560832a704c444af5585bc979db2e3](https://github.com/openimsdk/open-im-uniapp-demo/assets/35327293/4c47a0b7-e5d3-41ff-9e81-41ab3dbe2029)

**Comment by chen459236681** [comment]
> > > 这个弹窗 checkLoginError 只是用来处理 Chat 的错误，IM 的错误，直接把内容输出出来。
> > 
> > 
> > uni.showModal({ title: '看看SDK', content: IMSDK.nomalApi, success:(res)=> { if (res.confirm) { console.log('用户点击确定'); } else if (res.cancel) { console.log('用户点击取消'); } } });
> > 显示空白
> 
> ![image](https://private-user-images.githubusercontent.com/35327293/295775252-9ad3d6bf-113c-41d7-b01d-662dd48b01e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NDE5ODksIm5iZiI6MTcwNDk0MTY4OSwicGF0aCI6Ii8zNTMyNzI5My8yOTU3NzUyNTItOWFkM2Q2YmYtMTEzYy00MWQ3LWIwMWQtNjYyZGQ0OGIwMWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDAyNTQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5NGFlMWQxYmE1OTE5NWRlZTEyYmU4ZDMzZDYzM2FlZmY1MzA0MDZhYjZhOTk2MGRlYjcxYzNmMDZmMTczN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pubpKezH2epcInzl00-zaOQ0OYHunQdBSseCwP63a7M) ![image](https://private-user-images.githubusercontent.com/35327293/295775340-594b0503-5fb9-4046-adde-516afe611e91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NDE5ODksIm5iZiI6MTcwNDk0MTY4OSwicGF0aCI6Ii8zNTMyNzI5My8yOTU3NzUzNDAtNTk0YjA1MDMtNWZiOS00MDQ2LWFkZGUtNTE2YWZlNjExZTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDAyNTQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhNWJkMWU2NDM0MDgwMjYyZjkwM2UyMjljZGM1MDUzYjRmNWE2ZjJhMGU5MGE2ODk4OTc0ZmVmNTRmZDhjODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MKwT36-pWX3UKG1SGA5u3s4zqMY-sygU_QTFm60eiMs) ![e560832a704c444af5585bc979db2e3](https://private-user-images.githubusercontent.com/35327293/295775573-4c47a0b7-e5d3-41ff-9e81-41ab3dbe2029.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NDE5ODksIm5iZiI6MTcwNDk0MTY4OSwicGF0aCI6Ii8zNTMyNzI5My8yOTU3NzU1NzMtNGM0N2EwYjctZTVkMy00MWZmLTllODEtNDFhYjNkYmUyMDI5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDAyNTQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMzk2NzJmZTgwODJmZTNkMTkzYTBkMzFlNWQxYmE4MjdhM2U5OTc5Nzc1MTE1NTE0MGQxZDY4NTllNTlmNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UppbyUgdCKXo9MbXCMS1xl9XRUxuK1d3AJxUebnb57s)

![75cc742de95ef4bddd1f71f1d46cbbe](https://github.com/openimsdk/open-im-uniapp-demo/assets/35327293/f86e5d69-01fe-4243-a0bf-7e75bc927f47)
![image](https://github.com/openimsdk/open-im-uniapp-demo/assets/35327293/400a9f21-7d2a-46cd-a778-574282ae2f47)

**Comment by lgz5689** [comment]
uni项目中的本地插件截图

**Comment by chen459236681** [comment]
> uni项目中的本地插件截图

![image](https://github.com/openimsdk/open-im-uniapp-demo/assets/35327293/94f27a89-38be-4d5d-a76e-78a953b910ab)
![image](https://github.com/openimsdk/open-im-uniapp-demo/assets/35327293/13830b9e-6280-401c-b5e2-9a7f4731eb78)
