### ISSUE TITLE
Bug: <describe the error>

### ISSUE THREAD

**Issue by chen459236681** [openimsdk/open-im-uniapp-demo#51]
### What happened?

更改昵称后，对话框已发送后的昵称未变，想根据昵称判断角色无法实现

### What did you expect to happen?

1

### How can we reproduce it (as minimally and precisely as possible)?

1

### Anything else we need to know?

1

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by chen459236681** [comment]
![image](https://github.com/openimsdk/open-im-uniapp-demo/assets/35327293/a2f2e906-fe5e-41fc-9df9-b252e823e1bc)

**Comment by lgz5689** [comment]
不要使用昵称去判断 使用userID去判断 userID是唯一的

**Comment by chen459236681** [comment]
> 不要使用昵称去判断 使用userID去判断 userID是唯一的

![image](https://github.com/openimsdk/open-im-uniapp-demo/assets/35327293/d807a96f-decf-4f84-b241-fd9afe34886f)
我的需求是在对话框里，只获取对方聊天数据做些处理，然而没有区分是谁的字段，唯一不同的就是name了，但是如果我改了昵称，这边的还没改。不管怎么说也是个BUG。如果有userid最好，但是对话的数据没有us字段返回无法判断

**Comment by lgz5689** [comment]
可以通过sendID和recvID 判断消息是哪一方发送的

**Comment by lgz5689** [comment]
> 可以通过sendID和recvID 判断消息是哪一方发送的

SendID === 当前userID 拿就是自己发送的消息 否则就是对方发送的

**Comment by chen459236681** [comment]
> > 可以通过sendID和recvID 判断消息是哪一方发送的
> 
> SendID === 当前userID 拿就是自己发送的消息 否则就是对方发送的

OK明白，原来SendID 就是 当前userID。解决 ，谢谢
