### ISSUE TITLE
Bug: 调用黑名单api出现闪退

### ISSUE THREAD

**Issue by chen459236681** [openimsdk/open-im-uniapp-demo#53]
### What happened?

const funcName = this.checkedm ?
	IMSDK.IMMethods.AddBlack :
	IMSDK.IMMethods.RemoveBlack; 
IMSDK.asyncApi(funcName, IMSDK.uuid(), this.id)
	.catch((err) => this.showToast("操作失败"))
	.finally(() => (this.blackLoading = false));

在ios端，调用黑名单api出现闪退，X和11.。其他机型估计也是。安卓不会

### What did you expect to happen?

1

### How can we reproduce it (as minimally and precisely as possible)?

1

### Anything else we need to know?

1

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by lgz5689** [comment]
黑名单api 参数在3.5.1已经发生修改 [doc](https://docs.openim.io/zh-Hans/sdks/api/friend/addBlack)
