### ISSUE TITLE
Bug: h5运行的时候，无法登录

### ISSUE THREAD

**Issue by fushun1990** [openimsdk/open-im-uniapp-demo#54]
### What happened?

config.js
const registerUrl = 'http://188.8.9.223:10008'
const configUrl = 'http://188.8.9.223:10009'
const apiUrl = 'http://188.8.9.223:10002'

let wsUrl = ''

// #ifdef APP-PLUS
wsUrl = 'ws://188.8.9.223:10001'
// #endif

// #ifdef H5 || MP-WEIXIN
wsUrl = 'ws://188.8.9.223:10003'
// #endif

Login return information

{
	"data": "",
	"errCode": 10000,
	"event": "Login",
	"operationID": "p7wqpv1u4k1708433401587"
}

### What did you expect to happen?

Normal login

### How can we reproduce it (as minimally and precisely as possible)?

直接运行仓库代码

Run the warehouse code directly

### version

HBuilder X 3.99
npm 6.14.18 
node v14.21.3

### Cloud provider

HBuilder X 3.99
npm 6.14.18 
node v14.21.3

### OS version

HBuilder X 3.99
npm 6.14.18 
node v14.21.3

### Install tools

<details>
</details>

**Comment by lgz5689** [comment]
use "open-im-sdk": "^3.5.1-alpha.8"

**Comment by Loney-Cao** [comment]
应该服务端还需要运行 OIMWS 服务。https://github.com/openim-sigs/oimws

但是按照readme文档运行，make start 没有任何反应，不知哪里出了问题

**Comment by lgz5689** [comment]
> 应该服务端还需要运行 OIMWS 服务。https://github.com/openim-sigs/oimws
> 
> 但是按照readme文档运行，make start 没有任何反应，不知哪里出了问题

please create [issue](https://github.com/openim-sigs/oimws/issues/new) in OIMWS and Includes full logs and screenshots!

**Comment by lgz5689** [comment]
请之后的开发者 尽量选择最新的版本 [sdk-npm-version](https://www.npmjs.com/package/open-im-sdk?activeTab=versions) 同时搭配最新的 openim-server 和 最新的oimws
