### ISSUE TITLE
双方不是好友的情况下，会话列表用户更改了头像或者昵称列表的头像或者昵称能随之更为最新

### ISSUE THREAD

**Issue by Mo-JiuLi** [openimsdk/open-im-uniapp-demo#55]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [OpenIMSDK Slack](https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg) and got positive feedback

### Is this feature request related to a problem?

✅ Yes

### Problem Description

双方不是好友的情况下，当用户获取会话列表时，会话列表的用户头像、昵称无法获取最新的头像、昵称

### Solution Description

在获取会话列表时获取用户最新的头像、昵称

### Benefits

在获取会话列表时获取用户最新的头像、昵称

**Comment by lgz5689** [comment]
如果不是好友  当你查看对方用户信息  也就是调用 IM 的 getUsersInfoWithCache 的时候  如果对方的信息有变动的话  会触发会话改变  更新头像和昵称
