### ISSUE TITLE
Bug: h5登录成功后刷新一下又跳转到登录页面

### ISSUE THREAD

**Issue by delaiwen666** [openimsdk/open-im-uniapp-demo#56]
### What happened?

h5登录成功后刷新一下又跳转到登录页面,需要判断本地存在token就免登陆进去会话页面

### What did you expect to happen?

h5登录成功后刷新一下又跳转到登录页面,需要判断本地存在token就免登陆进去会话页面

### How can we reproduce it (as minimally and precisely as possible)?

h5登录成功后刷新一下又跳转到登录页面,需要判断本地存在token就免登陆进去会话页面

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by lgz5689** [comment]
https://github.com/openimsdk/open-im-uniapp-demo/commit/a29e8f10ec387f5ef691b97591e463cd1fb2a96f

**Comment by lgz5689** [comment]
> [a29e8f1](https://github.com/openimsdk/open-im-uniapp-demo/commit/a29e8f10ec387f5ef691b97591e463cd1fb2a96f)

应该是因为 login 和 tryLogin 的获取的平台号不一致 导致的刷新就退出登录状态
h5和小程序 使用不同的平台号
