### ISSUE TITLE
Docs: 10003端口请求进行补充

### ISSUE THREAD

**Issue by aidenup** [openimsdk/open-im-uniapp-demo#57]
### Description

使用10003 端口调用 SDK.login，调用不成功，返回错误信息-错误码 10000。
 + 在此文档中(https://doc.rentsoft.cn/zh-Hans/guides/gettingStarted/quickTestServer) 没有关于10003 端口的说明。
 + 在此文档(https://github.com/openimsdk/open-im-uniapp-demo?tab=readme-ov-file#%E6%9C%AC%E5%9C%B0%E5%BC%80%E5%8F%91-%EF%B8%8F) 提及了 "如果是 H5、小程序平台 websocket 地址端口为 10003" 
这部分有些不太明白

### Screenshots

![iwEdAqNwbmcDAQTRA50F0QEGBrDh_E4OLuFYzQYJk7mttBkAB9MAAAAAokRv3ggACaJpbQoAC9F_PA png_720x720q90](https://github.com/openimsdk/open-im-uniapp-demo/assets/110412617/478fee94-29d7-4bd2-9c06-08de9107da64)

**Comment by ilvcr** [comment]
我有同样的疑问，使用的docker部署服务，在镜像名为ghcr.io/openimsdk/openim-server:release-v3.6的容器中的/openim/openim-server/scripts/install/environment.sh脚本中，也没有发现相关10003的定义，请帮助我

**Comment by ilvcr** [comment]
我有同样的疑问，使用的docker部署服务，在镜像名为ghcr.io/openimsdk/openim-server:release-v3.6的容器中的/openim/openim-server/scripts/install/environment.sh脚本中，也没有发现相关10003的定义，请帮助我
environment.sh（节选）

PENIM_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)"

# 生成文件存放目录
LOCAL_OUTPUT_ROOT="${OPENIM_ROOT}/${OUT_DIR:-_output}"
source "${OPENIM_ROOT}/scripts/lib/init.sh"

#TODO: Access to the OPENIM_IP networks outside, or you want to use the OPENIM_IP network
# OPENIM_IP=127.0.0.1
if [ -z "${OPENIM_IP}" ]; then
  OPENIM_IP=$(openim::util::get_server_ip)
fi

# config.gateway custom bridge modes
# if [ -z "{IP_GATEWAY}" ] then
#     IP_GATEWAY=$(openim::util::get_local_ip)
# fi

function def() {
  local var_name="$1"
  local default_value="${2:-}"
  eval "readonly $var_name=\"\${$var_name:-$(printf '%q' "$default_value")}\""
}

# OpenIM Docker Compose 数据存储的默认路径
def "DATA_DIR" "${OPENIM_ROOT}"

# 设置统一的用户名，方便记忆
def "OPENIM_USER" "root"

# 设置统一的密码，方便记忆
readonly PASSWORD=${PASSWORD:-'openIM123'}

# 设置统一的数据库名称，方便管理
def "DATABASE_NAME" "openim_v3"

# Linux系统 openim 用户
def "LINUX_USERNAME" "openim"
readonly LINUX_PASSWORD=${LINUX_PASSWORD:-"${PASSWORD}"}

# 设置安装目录
def "INSTALL_DIR" "${LOCAL_OUTPUT_ROOT}/installs"
mkdir -p ${INSTALL_DIR}

def "ENV_FILE" "${OPENIM_ROOT}/scripts/install/environment.sh"

###################### Docker compose ###################
# OPENIM AND CHAT
def "CHAT_IMAGE_VERSION" "main"
def "SERVER_IMAGE_VERSION" "main"

# Choose the appropriate image address, the default is GITHUB image,
# you can choose docker hub, for Chinese users can choose Ali Cloud
# export IMAGE_REGISTRY="ghcr.io/openimsdk"
# export IMAGE_REGISTRY="openim"
# export IMAGE_REGISTRY="registry.cn-hangzhou.aliyuncs.com/openimsdk"
def "IMAGE_REGISTRY" "ghcr.io/openimsdk"
# def "IMAGE_REGISTRY" "openim"
# def "IMAGE_REGISTRY" "registry.cn-hangzhou.aliyuncs.com/openimsdk"

# Choose the appropriate image tag, the default is the latest version
def "SERVER_IMAGE_TAG" "latest"

###################### OpenIM Docker Network ######################
# 设置 Docker 网络的网段
readonly DOCKER_BRIDGE_SUBNET=${DOCKER_BRIDGE_SUBNET:-'172.28.0.0/16'}
IP_PREFIX=$(echo $DOCKER_BRIDGE_SUBNET | cut -d '/' -f 1)
SUBNET=$(echo $DOCKER_BRIDGE_SUBNET | cut -d '/' -f 2)
LAST_OCTET=$(echo $IP_PREFIX | cut -d '.' -f 4)

generate_ip() {
  local NEW_IP="$(echo $IP_PREFIX | cut -d '.' -f 1-3).$((LAST_OCTET++))"
  echo $NEW_IP
}
LAST_OCTET=$((LAST_OCTET + 1))
DOCKER_BRIDGE_GATEWAY=$(generate_ip)
LAST_OCTET=$((LAST_OCTET + 1))
MONGO_NETWORK_ADDRESS=$(generate_ip)
LAST_OCTET=$((LAST_OCTET + 1))
REDIS_NETWORK_ADDRESS=$(generate_ip)
LAST_OCTET=$((LAST_OCTET + 1))
KAFKA_NETWORK_ADDRESS=$(generate_ip)
LAST_OCTET=$((LAST_OCTET + 1))
ZOOKEEPER_NETWORK_ADDRESS=$(generate_ip)
LAST_OCTET=$((LAST_OCTET + 1))
MINIO_NETWORK_ADDRESS=$(generate_ip)
LAST_OCTET=$((LAST_OCTET + 1))
OPENIM_WEB_NETWORK_ADDRESS=$(generate_ip)
LAST_OCTET=$((LAST_OCTET + 1))
OPENIM_SERVER_NETWORK_ADDRESS=$(generate_ip)
LAST_OCTET=$((LAST_OCTET + 1))
OPENIM_CHAT_NETWORK_ADDRESS=$(generate_ip)
LAST_OCTET=$((LAST_OCTET + 1))
PROMETHEUS_NETWORK_ADDRESS=$(generate_ip)
LAST_OCTET=$((LAST_OCTET + 1))
GRAFANA_NETWORK_ADDRESS=$(generate_ip)
LAST_OCTET=$((LAST_OCTET + 1))
NODE_EXPORTER_NETWORK_ADDRESS=$(generate_ip)
LAST_OCTET=$((LAST_OCTET + 1))
OPENIM_ADMIN_FRONT_NETWORK_ADDRESS=$(generate_ip)
LAST_OCTET=$((LAST_OCTET + 1))
ALERT_MANAGER_NETWORK_ADDRESS=$(generate_ip)
###################### openim 配置 ######################
# read: https://github.com/openimsdk/open-im-server/blob/main/deployment/README.md
def "OPENIM_DATA_DIR" "/data/openim"
def "OPENIM_INSTALL_DIR" "/opt/openim"
def "OPENIM_CONFIG_DIR" "/etc/openim/config"
def "OPENIM_LOG_DIR" "/var/log/openim"
def "CA_FILE" "${OPENIM_CONFIG_DIR}/cert/ca.pem"

def "OPNEIM_CONFIG" "${OPENIM_ROOT}/config"
def "OPENIM_SERVER_ADDRESS" "${DOCKER_BRIDGE_GATEWAY}" # OpenIM服务地址

# OpenIM Websocket端口
readonly OPENIM_WS_PORT=${OPENIM_WS_PORT:-'10001'}

# OpenIM API端口
readonly API_OPENIM_PORT=${API_OPENIM_PORT:-'10002'}
def "API_LISTEN_IP" "0.0.0.0" # API的监听IP

###################### openim-chat 配置信息 ######################
def "OPENIM_CHAT_DATA_DIR" "./openim-chat/${CHAT_IMAGE_VERSION}"
def "OPENIM_CHAT_ADDRESS" "${DOCKER_BRIDGE_GATEWAY}" # OpenIM服务地址
def "OPENIM_CHAT_API_PORT" "10008"                   # OpenIM API端口
def "CHAT_API_LISTEN_IP" ""                          # OpenIM API的监听IP

def "OPENIM_ADMIN_API_PORT" "10009" # OpenIM Admin API端口
def "ADMIN_API_LISTEN_IP" ""        # OpenIM Admin API的监听IP

def "OPENIM_ADMIN_PORT" "30200" # OpenIM chat Admin端口
def "OPENIM_CHAT_PORT" "30300"  # OpenIM chat Admin的监听IP

def "OPENIM_ADMIN_NAME" "admin" # openim-chat Admin用户名
def "OPENIM_CHAT_NAME" "chat"   # openim-chat chat用户名

# TODO 注意： 一般的配置都可以使用 def 函数来定义，如果是包含特殊字符，比如说:
# TODO readonly MSG_DESTRUCT_TIME=${MSG_DESTRUCT_TIME:-'0 2 * * *'}
# TODO 使用 readonly 来定义合适，负责无法正常解析, 并且 yaml 模板需要加 "" 来包裹
###################### Env 配置信息 ######################
def "ENVS_DISCOVERY" "zookeeper"

###################### Zookeeper 配置信息 ######################
def "ZOOKEEPER_SCHEMA" "openim"                    # Zookeeper的模式
def "ZOOKEEPER_PORT" "12181"                       # Zookeeper的端口
def "ZOOKEEPER_ADDRESS" "${DOCKER_BRIDGE_GATEWAY}" # Zookeeper的地址
def "ZOOKEEPER_USERNAME" ""                        # Zookeeper的用户名
def "ZOOKEEPER_PASSWORD" ""                        # Zookeeper的密码

###################### MongoDB 配置信息 ######################
def "MONGO_URI"                                # MongoDB的URI
def "MONGO_PORT" "37017"                       # MongoDB的端口
def "MONGO_ADDRESS" "${DOCKER_BRIDGE_GATEWAY}" # MongoDB的地址
def "MONGO_DATABASE" "${DATABASE_NAME}"        # MongoDB的数据库名
def "MONGO_USERNAME" "root"                    # MongoDB的管理员身份用户名
# MongoDB的管理员身份密码
readonly MONGO_PASSWORD=${MONGO_PASSWORD:-"${PASSWORD}"}
# Mongo OpenIM 身份用户名
def "MONGO_OPENIM_USERNAME" "openIM"
# Mongo OpenIM 身份密码
readonly MONGO_OPENIM_PASSWORD=${MONGO_OPENIM_PASSWORD:-"${PASSWORD}"}

def "MONGO_MAX_POOL_SIZE" "100"                # 最大连接池大小

###################### Object 配置信息 ######################
# app要能访问到此ip和端口或域名
readonly API_URL=${API_URL:-"http://${OPENIM_IP}:${API_OPENIM_PORT}"}

def "OBJECT_ENABLE" "minio" # 对象是否启用
# 对象的API地址
readonly OBJECT_APIURL=${OBJECT_APIURL:-"${API_URL}"}
def "MINIO_BUCKET" "openim" # MinIO的存储桶名称
def "MINIO_PORT" "10005"    # MinIO的端口
# MinIO的端点URL
def MINIO_ADDRESS "${DOCKER_BRIDGE_GATEWAY}"
readonly MINIO_ENDPOINT=${MINIO_ENDPOINT:-"http://${MINIO_ADDRESS}:${MINIO_PORT}"}
def "MINIO_ACCESS_KEY" "${OPENIM_USER}"                                                  # MinIO的访问密钥ID
readonly MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-"${PASSWORD}"}
def "MINIO_SESSION_TOKEN"                                                         # MinIO的会话令牌
readonly MINIO_SIGN_ENDPOINT=${MINIO_SIGN_ENDPOINT:-"http://${OPENIM_IP}:${MINIO_PORT}"} # signEndpoint为minio公网地址
def "MINIO_PUBLIC_READ" "false"                                                   # 公有读

# 腾讯云COS的存储桶URL
def "COS_BUCKET_URL" "https://temp-1252357374.cos.ap-chengdu.myqcloud.com"
def "COS_SECRET_ID"                                                     # 腾讯云COS的密钥ID
def "COS_SECRET_KEY"                                                    # 腾讯云COS的密钥
def "COS_SESSION_TOKEN"                                                 # 腾讯云COS的会话令牌
def "COS_PUBLIC_READ" "false"                                           # 公有读
def "OSS_ENDPOINT" "https://oss-cn-chengdu.aliyuncs.com"                # 阿里云OSS的端点URL
def "OSS_BUCKET" "demo-9999999"                                         # 阿里云OSS的存储桶名称
def "OSS_BUCKET_URL" "https://demo-9999999.oss-cn-chengdu.aliyuncs.com" # 阿里云OSS的存储桶URL
def "OSS_ACCESS_KEY_ID"                                                 # 阿里云OSS的访问密钥ID
def "OSS_ACCESS_KEY_SECRET"                                             # 阿里云OSS的密钥
def "OSS_SESSION_TOKEN"                                                 # 阿里云OSS的会话令牌
def "OSS_PUBLIC_READ" "false"                                           # 公有读

#七牛云配置信息
def "KODO_ENDPOINT" "http://s3.cn-east-1.qiniucs.com"                    # 七牛云OSS的端点URL
def "KODO_BUCKET" "demo-9999999"                                         # 七牛云OSS的存储桶名称
def "KODO_BUCKET_URL" "http://your.domain.com"                           # 七牛云OSS的存储桶URL
def "KODO_ACCESS_KEY_ID"                                                 # 七牛云OSS的访问密钥ID
def "KODO_ACCESS_KEY_SECRET"                                             # 七牛云OSS的密钥
def "KODO_SESSION_TOKEN"                                                 # 七牛云OSS的会话令牌
def "KODO_PUBLIC_READ" "false"                                           # 公有读

# AWS Configuration Information
def "AWS_ENDPOINT" ""                                  # AWS endpoint, generally not needed unless using a specific service
def "AWS_REGION" "us-east-1"                           # AWS Region
def "AWS_BUCKET" "demo-9999999"                        # AWS S3 Bucket Name
def "AWS_ACCESS_KEY_ID"                                # AWS Access Key ID
def "AWS_SECRET_ACCESS_KEY"                            # AWS Secret Access Key
def "AWS_PUBLIC_READ" "false"                          # Public read access

###################### Redis 配置信息 ######################
def "REDIS_PORT" "16379"                                    # Redis的端口
def "REDIS_ADDRESS" "${DOCKER_BRIDGE_GATEWAY}"              # Redis的地址
def "REDIS_USERNAME"                                        # Redis的用户名
readonly REDIS_PASSWORD=${REDIS_PASSWORD:-"${PASSWORD}"}

###################### Kafka 配置信息 ######################
def "KAFKA_USERNAME"                                        # `Kafka` 的用户名
def "KAFKA_PASSWORD"                                        # `Kafka` 的密码
def "KAFKA_PORT" "19094"                                    # `Kafka` 的端口
def "KAFKA_ADDRESS" "${DOCKER_BRIDGE_GATEWAY}"              # `Kafka` 的地址
def "KAFKA_LATESTMSG_REDIS_TOPIC" "latestMsgToRedis"        # `Kafka` 的最新消息到Redis的主题
def "KAFKA_OFFLINEMSG_MONGO_TOPIC" "offlineMsgToMongoMysql" # `Kafka` 的离线消息到Mongo的主题
def "KAFKA_MSG_PUSH_TOPIC" "msgToPush"                      # `Kafka` 的消息到推送的主题
def "KAFKA_CONSUMERGROUPID_REDIS" "redis"                   # `Kafka` 的消费组ID到Redis
def "KAFKA_CONSUMERGROUPID_MONGO" "mongo"                   # `Kafka` 的消费组ID到Mongo
def "KAFKA_CONSUMERGROUPID_MYSQL" "mysql"                   # `Kafka` 的消费组ID到MySql
def "KAFKA_CONSUMERGROUPID_PUSH" "push"                     # `Kafka` 的消费组ID到推送

###################### openim-web 配置信息 ######################
def "OPENIM_WEB_PORT" "11001"                       # openim-web的端口

###################### openim-admin-front 配置信息 ######################
def "OPENIM_ADMIN_FRONT_PORT" "11002"                       # openim-admin-front的端口

###################### RPC 配置信息 ######################
def "RPC_REGISTER_IP"                               # RPC的注册IP
def "RPC_LISTEN_IP" "0.0.0.0"                       # RPC的监听IP

###################### prometheus 配置 ######################
def "PROMETHEUS_PORT" "19090"                       # Prometheus的端口
def "PROMETHEUS_ADDRESS" "${DOCKER_BRIDGE_GATEWAY}" # Prometheus的地址

###################### node-exporter 配置 ######################
def "NODE_EXPORTER_PORT" "19100"                       # node-exporter的端口
def "NODE_EXPORTER_ADDRESS" "${DOCKER_BRIDGE_GATEWAY}" # node-exporter的地址

###################### alertmanagerS 配置 ######################
def "ALERT_MANAGER_PORT" "19093"                       # node-exporter的端口
def "ALERT_MANAGER_ADDRESS" "${DOCKER_BRIDGE_GATEWAY}" # node-exporter的地址

###################### AlertManager Configuration Script ######################
# 解析超时
readonly ALERTMANAGER_RESOLVE_TIMEOUT=${ALERTMANAGER_RESOLVE_TIMEOUT:-'5m'}
# 发件人邮箱
readonly ALERTMANAGER_SMTP_FROM=${ALERTMANAGER_SMTP_FROM:-'alert@openim.io'}
# SMTP服务器地址和端口
readonly ALERTMANAGER_SMTP_SMARTHOST=${ALERTMANAGER_SMTP_SMARTHOST:-'smtp.163.com:465'}
# SMTP认证用户名
readonly ALERTMANAGER_SMTP_AUTH_USERNAME=${SMTP_USERNAME:-"alert@openim.io"}
# SMTP认证密码
readonly ALERTMANAGER_SMTP_AUTH_PASSWORD=${SMTP_PASSWORD:-"YOURAUTHPASSWORD"}
# SMTP是否需要TLS
readonly ALERTMANAGER_SMTP_REQUIRE_TLS=${ALERTMANAGER_SMTP_REQUIRE_TLS:-"false"}
# SMTP HELO/EHLO标识符
readonly ALERTMANAGER_SMTP_HELLO=${ALERTMANAGER_SMTP_HELLO:-"xxx监控告警"}
# 邮箱接收人
readonly ALERTMANAGER_EMAIL_TO=${ALERTMANAGER_EMAIL_TO:-"alert@example.com"}
# 邮箱主题
readonly ALERTMANAGER_EMAIL_SUBJECT=${ALERTMANAGER_EMAIL_SUBJECT:-"{EMAIL_SUBJECT:-'[Alert] Notification'}"}
# 是否发送已解决的告警
readonly ALERTMANAGER_SEND_RESOLVED=${ALERTMANAGER_SEND_RESOLVED:-"{SEND_RESOLVED:-'true'}"}

###################### Grafana 配置信息 ######################
def "GRAFANA_PORT" "13000"                        # Grafana的端口
def "GRAFANA_ADDRESS" "${DOCKER_BRIDGE_GATEWAY}" # Grafana的地址
###################### RPC Port Configuration Variables ######################
# For launching multiple programs, just fill in multiple ports separated by commas
# For example:
# readonly OPENIM_USER_PORT=${OPENIM_USER_PORT:-'10110, 10111, 10112'} #Try not to have Spaces

# OpenIM用户服务端口
readonly OPENIM_USER_PORT=${OPENIM_USER_PORT:-'10110'}
# OpenIM朋友服务端口
readonly OPENIM_FRIEND_PORT=${OPENIM_FRIEND_PORT:-'10120'}
# OpenIM消息服务端口
readonly OPENIM_MESSAGE_PORT=${OPENIM_MESSAGE_PORT:-'10130'}
# OpenIM消息网关服务端口
readonly OPENIM_MESSAGE_GATEWAY_PORT=${OPENIM_MESSAGE_GATEWAY_PORT:-'10140'}
# OpenIM组服务端口
readonly OPENIM_GROUP_PORT=${OPENIM_GROUP_PORT:-'10150'}
# OpenIM授权服务端口
readonly OPENIM_AUTH_PORT=${OPENIM_AUTH_PORT:-'10160'}
# OpenIM推送服务端口
readonly OPENIM_PUSH_PORT=${OPENIM_PUSH_PORT:-'10170'}
# OpenIM对话服务端口
readonly OPENIM_CONVERSATION_PORT=${OPENIM_CONVERSATION_PORT:-'10180'}
# OpenIM第三方服务端口
readonly OPENIM_THIRD_PORT=${OPENIM_THIRD_PORT:-'10190'}

**Comment by ilvcr** [comment]
我有同样的疑问，使用的docker部署服务，在镜像名为ghcr.io/openimsdk/openim-server:release-v3.6的容器中的/openim/openim-server/scripts/install/environment.sh脚本中，也没有发现相关10003的定义，请帮助我
environment.sh（节选）

###### OpenIM Websocket端口
readonly OPENIM_WS_PORT=${OPENIM_WS_PORT:-'10001'}

###### OpenIM API端口
readonly API_OPENIM_PORT=${API_OPENIM_PORT:-'10002'}
def "API_LISTEN_IP" "0.0.0.0" # API的监听IP

###################### openim-chat 配置信息 ######################
def "OPENIM_CHAT_DATA_DIR" "./openim-chat/${CHAT_IMAGE_VERSION}"
def "OPENIM_CHAT_ADDRESS" "${DOCKER_BRIDGE_GATEWAY}" # OpenIM服务地址
def "OPENIM_CHAT_API_PORT" "10008"                   # OpenIM API端口
def "CHAT_API_LISTEN_IP" ""                          # OpenIM API的监听IP

def "OPENIM_ADMIN_API_PORT" "10009" # OpenIM Admin API端口
def "ADMIN_API_LISTEN_IP" ""        # OpenIM Admin API的监听IP

def "OPENIM_ADMIN_PORT" "30200" # OpenIM chat Admin端口
def "OPENIM_CHAT_PORT" "30300"  # OpenIM chat Admin的监听IP

def "OPENIM_ADMIN_NAME" "admin" # openim-chat Admin用户名
def "OPENIM_CHAT_NAME" "chat"   # openim-chat chat用户名

###### TODO 注意： 一般的配置都可以使用 def 函数来定义，如果是包含特殊字符，比如说:
###### TODO readonly MSG_DESTRUCT_TIME=${MSG_DESTRUCT_TIME:-'0 2 * * *'}
###### TODO 使用 readonly 来定义合适，负责无法正常解析, 并且 yaml 模板需要加 "" 来包裹
###################### Env 配置信息 ######################
def "ENVS_DISCOVERY" "zookeeper"

###################### Zookeeper 配置信息 ######################
def "ZOOKEEPER_SCHEMA" "openim"                    # Zookeeper的模式
def "ZOOKEEPER_PORT" "12181"                       # Zookeeper的端口
def "ZOOKEEPER_ADDRESS" "${DOCKER_BRIDGE_GATEWAY}" # Zookeeper的地址
def "ZOOKEEPER_USERNAME" ""                        # Zookeeper的用户名
def "ZOOKEEPER_PASSWORD" ""                        # Zookeeper的密码

###################### MongoDB 配置信息 ######################
def "MONGO_URI"                                # MongoDB的URI
def "MONGO_PORT" "37017"                       # MongoDB的端口
def "MONGO_ADDRESS" "${DOCKER_BRIDGE_GATEWAY}" # MongoDB的地址
def "MONGO_DATABASE" "${DATABASE_NAME}"        # MongoDB的数据库名
def "MONGO_USERNAME" "root"                    # MongoDB的管理员身份用户名
###### MongoDB的管理员身份密码
readonly MONGO_PASSWORD=${MONGO_PASSWORD:-"${PASSWORD}"}
###### Mongo OpenIM 身份用户名
def "MONGO_OPENIM_USERNAME" "openIM"
###### Mongo OpenIM 身份密码
readonly MONGO_OPENIM_PASSWORD=${MONGO_OPENIM_PASSWORD:-"${PASSWORD}"}

def "MONGO_MAX_POOL_SIZE" "100"                # 最大连接池大小


###### OpenIM用户服务端口
readonly OPENIM_USER_PORT=${OPENIM_USER_PORT:-'10110'}
###### OpenIM朋友服务端口
readonly OPENIM_FRIEND_PORT=${OPENIM_FRIEND_PORT:-'10120'}
###### OpenIM消息服务端口
readonly OPENIM_MESSAGE_PORT=${OPENIM_MESSAGE_PORT:-'10130'}
###### OpenIM消息网关服务端口
readonly OPENIM_MESSAGE_GATEWAY_PORT=${OPENIM_MESSAGE_GATEWAY_PORT:-'10140'}
###### OpenIM组服务端口
readonly OPENIM_GROUP_PORT=${OPENIM_GROUP_PORT:-'10150'}
###### OpenIM授权服务端口
readonly OPENIM_AUTH_PORT=${OPENIM_AUTH_PORT:-'10160'}
###### OpenIM推送服务端口
readonly OPENIM_PUSH_PORT=${OPENIM_PUSH_PORT:-'10170'}
###### OpenIM对话服务端口
readonly OPENIM_CONVERSATION_PORT=${OPENIM_CONVERSATION_PORT:-'10180'}
###### OpenIM第三方服务端口
readonly OPENIM_THIRD_PORT=${OPENIM_THIRD_PORT:-'10190'}
