### ISSUE TITLE
[BUG] OnRecvOfflineNewMessage 退出后台后接受不到新消息推送

### ISSUE THREAD

**Issue by AINIbb** [openimsdk/open-im-uniapp-demo#58]
### OpenIM Server Version

3.5。2

### Operating System and CPU Architecture

macOS (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

OnRecvOfflineNewMessage 退出后台后接受不到新消息推送
在onHide 方法里设置了 IMSDK.asyncApi(IMSDK.IMMethods.SetAppBackgroundStatus, IMSDK.uuid(), true);
在基座调试时 应用退出后台后新消息推送的还是OnRecvNewMessages 回掉，但是打正式包后就不推送了

### Screenshots Link

![WechatIMG713](https://github.com/openimsdk/open-im-uniapp-demo/assets/87977389/0f91fe9a-7216-4260-9fad-edeea87632c3)
![WechatIMG714](https://github.com/openimsdk/open-im-uniapp-demo/assets/87977389/d2afedef-0607-47d4-9ad6-9e6274dbe0c5)

**Comment by lgz5689** [comment]
接入个推
