### ISSUE TITLE
demo 错误

### ISSUE THREAD

**Issue by ltsj404** [OpenIMSDK/Open-IM-Uniapp-Demo#6]
Open-IM-uniapp/pages/conversation/chatWin.vue

调用函数位置
```
markC2CRead(this.vuex_conversation.userID, uids)
```
应该改为
```
this.markC2CRead(this.vuex_conversation.userID, cids)
```

**Comment by r0103** [comment]
兄弟，请教一下，你那里调试通了吗？有踩坑记录嘛？

**Comment by ltsj404** [comment]
> 

可以运行的，修改上面对应的代码就可以了

**Comment by r0103** [comment]
奇怪了，我是注册发送短信那里调试不同，必须用官方那个ip发送和接收短信吗？

**Comment by ltsj404** [comment]
> 奇怪了，我是注册发送短信那里调试不同，必须用官方那个ip发送和接收短信吗？

如果是docker compose 运行的，官网的demo 好像有带有注册、短信接口路由的，如果只看openim-sdk-server ，我没有找到这两个路由，猜测是需要自己写（如果需要）

**Comment by Bloomingg** [comment]
已修改，感谢指正
