### ISSUE TITLE
[RFC]: uniapp版本，在打包成IOS端时，没有音视频功能

### ISSUE THREAD

**Issue by hosiks66** [openimsdk/open-im-uniapp-demo#60]
![2331720667007_ pic](https://github.com/openimsdk/open-im-uniapp-demo/assets/11973283/c8572f7a-de86-4554-90ee-babcd30b5ee4)

**Comment by hosiks66** [comment]
安卓的打包也是没有的

**Comment by lgz5689** [comment]
The audio and video features belong to the commercial version and are not open source.
