### ISSUE TITLE
[BUG] 配置域名访问后，图片无法发送

### ISSUE THREAD

**Issue by pangganboy** [openimsdk/open-im-uniapp-demo#61]
### OpenIM Server Version

eg.3.7

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

使用域名部署，参照文档改了 open-im-server/config/config.yaml 修改 Minio 对应的内容，也改了env文件以及nginx配置，后续就出现了文字能正常发送，但是图片发送失败，且提示cors
![cd6898e16efe48757a717c8deb98332](https://github.com/user-attachments/assets/0a81aba6-93db-4718-9c4c-04adb326d4c2)

**Comment by lgz5689** [comment]
This is a server issue. Please go to [open-im-server](https://github.com/openimsdk/open-im-server/issues/new/choose) to create an issue.
