### ISSUE TITLE
[BUG] 获取不到好友

### ISSUE THREAD

**Issue by hemingmin** [openimsdk/open-im-uniapp-demo#63]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

OpenIM SDK 3.5.0时，获取好友及群组是正常的。更新新版之后，获取不到好友。没有报错，返回空数组。
```js
IMSDK
.asyncApi(IMSDK.IMMethods.GetFriendList, uuidv4())
.then(({ data }) => {
console.log("好友data",data)
const friendInfoList = data.map(item => item.friendInfo)
console.log("好友",friendInfoList)
commit('SET_FRIEND_LIST', friendInfoList)
}).catch(err => {
console.log("获取通讯录失败",err)
})
```

**Comment by lgz5689** [comment]
保证服务端和客户端版本一致

**Comment by hemingmin** [comment]
好的，我看新版服务端使用mongodb有更新指南吗

**Comment by lgz5689** [comment]
你可以去服务端仓库提issue
