### ISSUE TITLE
[BUG] 运行闪退

### ISSUE THREAD

**Issue by XieZhouXin** [openimsdk/open-im-uniapp-demo#65]
### OpenIM Server Version

v3.8

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

![Uploading 3567bd2ecc45bd7f8d2d59477bc2fac.png…]()

### Screenshots Link

报Error: Not Found：Page[4][-1;-1,3,4-1;si_3948177615_5359802029,0] at view.umd.min.js:1

**Comment by XieZhouXin** [comment]
报Error: Not Found：Page[4][-1;-1,3,4-1;si_3948177615_5359802029,0] at view.umd.min.js:1
基座运行都报错

**Comment by lgz5689** [comment]
你照片上传失败了，另外这个报错不影响，需要按照文档打自定义基座

> 报Error: Not Found：Page[4][-1;-1,3,4-1;si_3948177615_5359802029,0] at view.umd.min.js:1 基座运行都报错
