### ISSUE TITLE
[BUG] 登录问题

### ISSUE THREAD

**Issue by nailuox** [openimsdk/open-im-uniapp-demo#68]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

oimws 根据源码构建
openim-server 3.7
open-im-uniapp-demo v2 分支
h5 app登录不了

oimws 根据源码构建
openim-server 3.8.1
open-im-uniapp-demo master 分支
h5 app登录后getFriendListPage getJoinedGroupListPage报错

### Screenshots Link

![image](https://github.com/user-attachments/assets/15936c4d-804d-4707-bdad-e8a062df1330)

**Comment by lgz5689** [comment]
这个是3.8.1的apis uniapp运行h5/小程序 仅能使用3.8.0以前的apis 看控制台的第三条warn
