### ISSUE TITLE
[BUG] 使用HbuilderX打包后运行时在登录后闪退

### ISSUE THREAD

**Issue by StrangerYanYu** [openimsdk/open-im-uniapp-demo#69]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

Windows (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

使用uniapp demo选择云端插件的OpenIM SDK,打包成自定义基座运行，在模拟器上运行时会在登录账号后显示同步中，随后闪退，真机运行在荣耀90 GT上时登录账号后立刻闪退

**Comment by StrangerYanYu** [comment]
没有错误提示

**Comment by StrangerYanYu** [comment]
疑似最近4-5天新出现的问题，过去运行时没有遇到这个问题

**Comment by lgz5689** [comment]
更新到最新的SDK，同时确保你客户端SDK和服务端版本一致

**Comment by lgz5689** [comment]
> 程序控制台没有报错

使用logcat收集日志
