### ISSUE TITLE
[BUG] ios收消息很慢 3.8.2

### ISSUE THREAD

**Issue by youlixiangbhc** [openimsdk/open-im-uniapp-demo#70]
### OpenIM Server Version

3.8.2

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

ios最新版插件收消息很慢
app控制台信息：
1 [Object] {"errMsg":"","errCode":0,"data":0}  at store/modules/conversation.js:96
10:13:48.382 Error: Not Found：Page[4][-1;-1,3,4-0;sg_2656146884,0]
10:13:48.382 Error: Not Found：Page[4][-1;-1,3,4-1;si_2039265376_5902243716,0]
10:13:58.487 [Object] {"errMsg":"","errCode":0,"data":0}  at store/modules/conversation.js:96
10:13:58.487 Error: Not Found：Page[4][-1;-1,3,4-0;sg_2656146884,0]
10:13:58.487 Error: Not Found：Page[4][-1;-1,3,4-1;si_2039265376_5902243716,0]
10:14:05.579 [Object] {"clientMsgID":"47ee3a7b6fc077c23d05fc1b47cd5329","createTime":1730081649573,"sendTime":173...} at pages/conversation/chating/components/ChatingFooter/index.vue:196
10:14:05.579 [Object] {"clientMsgID":"47ee3a7b6fc077c23d05fc1b47cd5329","createTime":1730081649573,"sendTime":173...} at pages/conversation/chating/components/ChatingFooter/index.vue:213
10:14:05.580 [Object] [{"clientMsgID":"c3827e0118e9c4701fcf7dbc898e4e91","serverMsgID":"d8b6ddd27e551ccf047582baa...} at pages/conversation/chating/components/ChatingList.vue:73
10:14:05.580 [Object] [{"unreadCount":0,"groupAtType":0,"isPrivateChat":false,"groupID":"","isNotInGroup":false,"...} at App.vue:449
10:14:05.580 Error: Not Found：Page[4][-1;-1,3,4-1;si_2039265376_5902243716,0]
10:14:05.580 [Object] [{"clientMsgID":"c3827e0118e9c4701fcf7dbc898e4e91","serverMsgID":"d8b6ddd27e551ccf047582baa...} at pages/conversation/chating/components/ChatingList.vue:73
10:14:05.580 [Object] [{"unreadCount":0,"groupAtType":0,"isPrivateChat":false,"groupID":"","isNotInGroup":false,"...} at App.vue:449
10:14:05.580 Error: Not Found：Page[4][-1;-1,3,4-1;si_2039265376_5902243716,0]
10:14:05.580 [Object] [{"unreadCount":0,"groupAtType":0,"isPrivateChat":false,"groupID":"","isNotInGroup":false,"...} at App.vue:449
10:14:05.580 Error: Not Found：Page[4][-1;-1,3,4-1;si_2039265376_5902243716,0]
10:14:10.659 unload at pages/conversation/chating/index.vue:50
10:14:10.660 unload at pages/conversation/chating/index.vue:50
10:14:10.660 [JS Framework] Failed to execute the callback function:
10:14:10.660 TypeError: null is not an object (evaluating 'e.__preload__') __ERROR
10:14:11.713 [Object] []  at pages/conversation/chating/components/ChatingList.vue:73
10:14:11.713 TypeError: undefined is not an object (evaluating 'r.data.attrs._i')
10:14:11.713 getHistoryMesageList::: at store/modules/message.js:32
10:14:11.713 [Object] {"conversationID":"si_2039265376_5902243716","userID":"","groupID":"","count":20,"startClie...} at store/modules/message.js:33
10:14:11.714 [Object] []  at pages/conversation/chating/components/ChatingList.vue:73
10:14:11.714 getOnlineState,  [Object] [{"userID":"2039265376","status":0,"platformIDs":[]}]  at pages/conversation/chating/components/ChatingHeader.vue:155
10:14:21.815 [Object] {"messageList":[{"clientMsgID":"c3827e0118e9c4701fcf7dbc898e4e91","serverMsgID":"d8b6ddd27e...} at store/modules/message.js:39
10:14:21.815 [Object] [{"clientMsgID":"c3827e0118e9c4701fcf7dbc898e4e91","serverMsgID":"d8b6ddd27e551ccf047582baa...} at pages/conversation/chating/components/ChatingList.vue:73
10:14:31.939 [Object] {"errMsg":"","errCode":0,"data":0}  at store/modules/conversation.js:96
10:14:31.939 Error: Not Found：Page[5][-1;-1,3,4-0;sg_2656146884,0]
10:14:31.939 Error: Not Found：Page[5][-1;-1,3,4-1;si_2039265376_5902243716,0]
10:14:42.031 [Object] {"errMsg":"","errCode":0,"data":0}  at store/modules/conversation.js:96
10:14:42.031 Error: Not Found：Page[5][-1;-1,3,4-0;sg_2656146884,0]
10:14:42.031 Error: Not Found：Page[5][-1;-1,3,4-1;si_2039265376_5902243716,0]
10:14:52.129 [Object] {"errMsg":"","errCode":0,"data":0}  at store/modules/conversation.js:96
10:14:52.130 Error: Not Found：Page[5][-1;-1,3,4-0;sg_2656146884,0]
10:14:52.130 Error: Not Found：Page[5][-1;-1,3,4-1;si_2039265376_5902243716,0]

有时候登录时还会报这个错 需要重新安装才行 ios：

{
    "mobile": "1300000000",
    "password": "c4ca4238a0b923820dcc509a6f75849b",
    "platform": 1,
    "areaCode": "+86",
    "smsCode": "1",
    "msg_id": 0
}

10:09:12.505 登录失败,  [Number] 10005 ,  error *errors.withStack not implement CodeError: init database initDB failed /var/mobile/Containers/Data/Application/DA01BDFA-5C15-4D82-B6A8-1A15DD017FF6/Documents/Pandora/apps/946E3395734C599DB4EEED397729470E/doc/user/: open db failed /var/mobile/Containers/Data/Application/DA01BDFA-5C15-4D82-B6A8-1A15DD017FF6/Documents/Pandora/apps/946E3395734C599DB4EEED397729470E/doc/user/OpenIM_v3_5902243716.db: unable to open database file: no such file or directory: 10006 Internal SDK error at pages/login/index.vue:255

**Comment by lgz5689** [comment]
更新到最新的SDK，同时确保你客户端SDK和服务端版本一致

**Comment by youlixiangbhc** [comment]
感谢回复：
我之前服务端用的 docker 部署 看了好像版本对不上， 请问只有切换到源码部署才能使用 3.8 的客户端吗

**Comment by lgz5689** [comment]
保证客户端SDK和服务端版本一致即可
