### ISSUE TITLE
[BUG] ，H5转发报这个20000错误

### ISSUE THREAD

**Issue by lianfu520** [openimsdk/open-im-uniapp-demo#71]
### OpenIM Server Version

3.7.0

### Operating System and CPU Architecture

Windows (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

H5转发报这个20000错误。
{
    "event": "CreateQuoteMessage",
    "errCode": 20000,
    "errMsg": "==> github.com/openim-sigs/oimws/pkg/module.(*JsCore).SendMsg()@67: args has nil: args[1] is not nil",
    "data": "",
    "operationID": "{\"clientMsgID\":\"d1ce1cd13b15c9b198bcecacbce469fa\",\"serverMsgID\":\"42c977b866388fcb0ddc9fbf5dce2e82\",\"createTime\":1730187842368,\"sendTime\":1730187842407,\"sessionType\":1,\"sendID\":\"13902864868\",\"recvID\":\"15381539216\",\"msgFrom\":100,\"contentType\":101,\"senderPlatformID\":5,\"senderNickname\":\"张龙\",\"senderFaceUrl\":\"https://im.b2byb.com/api/object/13902864868/动态空压BU.png\",\"seq\":39,\"isRead\":false,\"status\":2,\"textElem\":{\"content\":\"好的呢！\"},\"attachedInfoElem\":{\"groupHasReadInfo\":{\"hasReadCount\":0,\"groupMemberCount\":0},\"isPrivateChat\":false,\"burnDuration\":0,\"hasReadTime\":0,\"isEncryption\":false,\"inEncryptStatus\":false}}"
}

**Comment by lgz5689** [comment]
OIMWS目前已经废弃，不再进行维护，请等待新的jssdk。如果你使用uniapp vue3版本只开发H5一个平台，可以考虑换成https://github.com/openimsdk/open-im-sdk-web-wasm
