### ISSUE TITLE
[BUG] demo的添加好友功能存在问题 ; openim-uniapp-polyfill包中好友获取相关功能有问题，获取不到好友

### ISSUE THREAD

**Issue by StrangerYanYu** [openimsdk/open-im-uniapp-demo#72]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

Windows (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

好友添加功能问题：输入目标手机号或用户ID后点击搜索，不会显示“未搜索到相关结果”，也不会跳到对应用户页面，经检查发现是/pages/common/searchUserOrGroup页面代码第112及114行左右问题：
 112行问题：“getUsersInfoWithCache”关键字在openim-uniaoo-polyfill包中并未找到对应内容，改为了“getUsersInfo"
 114行问题：前端小白不确定是什么问题，将所需的参数提前赋值并普通放入函数中
做出以上修改后能够正常使用；
![好友添加代码修改前](https://github.com/user-attachments/assets/79ff99d7-d0c7-4dd8-a50f-6e528acbc7ca)
![好友添加代码修改后](https://github.com/user-attachments/assets/08e9bd0f-5fc5-477a-b73b-b15cce70352e)
希望能作为参考。

好友获取问题：
通讯录-我的好友页面没有获取到好友，
尝试了各种方法，尝试了store的getFriendList方法未能正常使用,于是直接使用IMSDK.asyncapi尝试了getFriendList和getFriendListPage，都未能解决办法，连接的数据库的friend表中确认有对应数据，希望能看一下
![数据库好友表](https://github.com/user-attachments/assets/2548b336-be6c-4f80-bfe9-326b4394c663)

**Comment by lgz5689** [comment]
你运行的是安卓端吗，调用`getFriendList `和`getFriendListPage `的时候，通过`logcat`收集日志。
