### ISSUE TITLE
[BUG] 调用uniapp SDK  getAdvancedHistoryMessageList接口获取会话中的历史聊天记录回调AdvancedHistoryInfo时出现错误

### ISSUE THREAD

**Issue by yuazhliu** [openimsdk/open-im-uniapp-demo#73]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

回调返回结果： "errcode": 100,errMsg":"10001 Network timeout error'
![openim_getAdvancedHistoryMessageList](https://github.com/user-attachments/assets/d56f8289-e0b2-4897-bf8f-c6695c76a175)

**Comment by lgz5689** [comment]
提供服务器部署方式、版本，客户端SDK版本，是自行接入SDK，还是基于Demo二次开发，有没有修改代码，Uniapp运行的是哪个平台

**Comment by yuazhliu** [comment]
用hbuilderx自定义基座运行在安卓真机上，SDK版本是跟demo一致3.5.2,基于demo二次开发，错误模块并未修改代码调用方式与demo一致，发这个问题的条件是：我用两台真机调试，然后注册账号收发消息及获取历史记录都是正常，但是两台真机互换一下账号登录然后获取聊天历史记录的时候抛的异常，数据有返回但是条数不对只返回了一条数据，然后回调异常errCode:100,如果在不换手机登录聊天及获取历史数据的话读取历史记录没有问题数据返回正常。
------------------&nbsp;原始邮件&nbsp;------------------



发件人:                                                                                                                        "openimsdk/open-im-uniapp-demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月12日(星期二) 晚上6:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openimsdk/open-im-uniapp-demo] [BUG] 调用uniapp SDK  getAdvancedHistoryMessageList接口获取会话中的历史聊天记录回调AdvancedHistoryInfo时出现错误 (Issue #73)





 
提供服务器部署方式、版本，客户端SDK版本，是自行接入SDK，还是基于Demo二次开发，有没有修改代码，Uniapp运行的是哪个平台

**Comment by lgz5689** [comment]
OpenIM Server Version 3.8.0？

**Comment by yuazhliu** [comment]
是的 server是3.8.0




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kevin ***@***.***&gt;; 
发送时间: 2024年11月13日(星期三) 上午10:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [openimsdk/open-im-uniapp-demo] [BUG] 调用uniapp SDK  getAdvancedHistoryMessageList接口获取会话中的历史聊天记录回调AdvancedHistoryInfo时出现错误 (Issue #73)














 
OpenIM Server Version 3.8.0？

**Comment by lgz5689** [comment]
保持Server和SDk版本一致

**Comment by yuazhliu** [comment]
OK 我把SDK换成3.8.0的试试



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kevin ***@***.***&gt;; 
发送时间: 2024年11月13日(星期三) 上午10:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [openimsdk/open-im-uniapp-demo] [BUG] 调用uniapp SDK  getAdvancedHistoryMessageList接口获取会话中的历史聊天记录回调AdvancedHistoryInfo时出现错误 (Issue #73)














 
保持Server和SDk版本一致

**Comment by yuazhliu** [comment]
客户端SDK没有3.8.0的依赖吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openimsdk/open-im-uniapp-demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月13日(星期三) 上午10:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openimsdk/open-im-uniapp-demo] [BUG] 调用uniapp SDK  getAdvancedHistoryMessageList接口获取会话中的历史聊天记录回调AdvancedHistoryInfo时出现错误 (Issue #73)





 
保持Server和SDk版本一致

**Comment by lgz5689** [comment]
插件市场下载

**Comment by yuazhliu** [comment]
我SDK用是云端最新插件，但是依赖是3.5.2的可以这样用吗





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openimsdk/open-im-uniapp-demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月14日(星期四) 中午12:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openimsdk/open-im-uniapp-demo] [BUG] 调用uniapp SDK  getAdvancedHistoryMessageList接口获取会话中的历史聊天记录回调AdvancedHistoryInfo时出现错误 (Issue #73)





 
插件市场下载

**Comment by lgz5689** [comment]
最新的云插件就可以

**Comment by yuazhliu** [comment]
我这边uniapp调用修改群信息setGroupInfor然后抛出异常，是什么情况。







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openimsdk/open-im-uniapp-demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月14日(星期四) 下午2:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openimsdk/open-im-uniapp-demo] [BUG] 调用uniapp SDK  getAdvancedHistoryMessageList接口获取会话中的历史聊天记录回调AdvancedHistoryInfo时出现错误 (Issue #73)





 
最新的云插件就可以

**Comment by lgz5689** [comment]
请提供相关的错误异常、sdk日志和logcat日志。

**Comment by lgz5689** [comment]
请提供相关的错误异常、sdk日志和logcat日志。
