### ISSUE TITLE
[BUG] uniapp-demo源码运行，账号登陆提示login repeat

### ISSUE THREAD

**Issue by szyuanyang** [openimsdk/open-im-uniapp-demo#75]
### OpenIM Server Version

3.3.4

### Operating System and CPU Architecture

Windows (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

运行uniapp-demo源码，H5登陆提示重复登陆，但是确定没有登陆。
16:14:54.562 {event: "Login", operationID: "w68xs692o71732608894554", data: null, errMsg: "login repeat", errCode: 10102} at pages/login/index.vue:231

**Comment by lgz5689** [comment]
你是不是修改代码之后热更新直接就使用了？

**Comment by szyuanyang** [comment]
是的，就把服务器IP地址改了直接运行的

**Comment by lgz5689** [comment]
dev环境，修改完代码，需要手动刷新页面。

**Comment by szyuanyang** [comment]
我点的 运行到Chrome，页面刷新好多次了哦

**Comment by lgz5689** [comment]
你的代码是什么时候拉的，服务端换成3.8.2，然后拉最新的Demo代码

**Comment by szyuanyang** [comment]
好的，我看看

**Comment by zsjinwei** [comment]
昨天合并代码后H5环境, 服务端3.8.2, 我也是遇到login repeat, APP环境没问题, H5要清空redis的token才能登录, 但是第二次发起登录又出现login repeat, 而且我发现即使不出现login repeat:        IMSDK.asyncApi(IMSDK.IMMethods.Login, IMSDK.uuid(), {
          userID: IMUserID,
          token: IMToken,
          platformID,
          wsAddr: config.getIMWsUrl(),
          apiAddr: config.getIMApiUrl(),
        })
          .then((res) => {
            console.log('success', res)
            initStore()
          })
          .catch((err) => {console.error(err)}) 这里then和catch都不会回调, 好像是ws没有消息下来导致的

**Comment by szyuanyang** [comment]
哎，搞不定都更新了还是10:54:03.122 {event: "Login", operationID: "z7zy42s7mn1732676043114", data: null, errMsg: "login repeat", errCode: 10102}，我看了服务器上面redis的keys也是空的

**Comment by szyuanyang** [comment]
我试了运行微信小程序也是这个错误

**Comment by szyuanyang** [comment]
刚开始运行提示：
{event: "Login", operationID: "b662fa2o1o1732678268935", data: null, errMsg: "network error", errCode: 10000}(env: Windows,mp,1.06.2409140; lib: 3.6.6)
第二次点登陆就会提示：
 {event: "Login", operationID: "z7zy42s7mn1732676043114", data: null, errMsg: "login repeat", errCode: 10102}

**Comment by lgz5689** [comment]
可以尝试吧浏览器local storage清除一下 或者使用无痕浏览器尝试

**Comment by szyuanyang** [comment]
C:\Users\win 10>telnet 110.41.49.114 10003
正在连接110.41.49.114...无法打开到主机的连接。 在端口 10003: 连接失败

wsUrl = 'ws://110.41.49.114:10003'
是不是ws服务连接不上导致的啊，单位我吧服务器的这个端口有开放还是不行，是不是这个端口有误呢？

> 可以尝试吧浏览器local storage清除一下 或者使用无痕浏览器尝试

**Comment by lgz5689** [comment]
你代码是旧的，3.8.2已经是用10001的

**Comment by szyuanyang** [comment]
我110.41.49.114 10001是可以连接的，你指的是服务器端的代码是旧的还是uniapp-demo代码是旧的啊，服务器端的版本在哪里可以看到

**Comment by szyuanyang** [comment]
等等，我重新下载最新的，好像不一样

**Comment by szyuanyang** [comment]
我现在更新了最新的uniapp-demo，运行可以登陆了，但是登陆后提示14:47:35.075 ‍[⁠Error⁠]‍ {message: "Not Found"}，消息同步失败
14:49:07.147 ‍[⁠Error⁠]‍ {message: "Not Found"}
14:49:07.147 %cSDK =>%c [OperationID:] (event) trigger OnSyncServerFailed with data null errCode 10006 errMsg Not Found

**Comment by lgz5689** [comment]
确认服务端版本是否为3.8.2

**Comment by szyuanyang** [comment]
> 确认服务端版本是否为3.8.2

服务器端能增量更新吗，还是需要下载最新的重新部署呢？

**Comment by lgz5689** [comment]
拉新代码，然后重新部署

**Comment by szyuanyang** [comment]
@lgz5689 我拉取了最新的服务器源码，部署后出现下面错误
16:34:38.141 %cSDK =>%c [OperationID:dv451d7yjo1732696477859] (response) run getGroupApplicationListAsApplicant with error {"event":"GetGroupApplicationListAsApplicant","operationID":"dv451d7yjo1732696477859","data":null,"errMsg":"1507 TokenNotExistError","errCode":10006} font-size:14px; background:#28A745; border-radius:4px; padding-inline:4px; 
16:34:54.506 {errCode: 1001, errMsg: "ArgsError", errDlt: "header must have token: 1001 ArgsError"}

同时登陆后台chatAdmin提示账号不存在，openim-web-front前端也注册登陆不了，提示header must have token: 1001 ArgsError

**Comment by szyuanyang** [comment]
源码部署，按这个来弄的
https://docs.openim.io/zh-Hans/guides/gettingStarted/imSourceCodeDeployment

**Comment by lgz5689** [comment]
切换到 release-v3.8.2 分支

**Comment by szyuanyang** [comment]
> 切换到 release-v3.8.2 分支

git clone -b release-v3.8.2 https://github.com/openimsdk/open-im-server && cd open-im-server
我这样重新拉取后编译部署了还是那样哦，应该是这个分支的最新代码了吧
![微信截图_20241127165903](https://github.com/user-attachments/assets/9bdc5979-50ec-4d40-8024-272a8179765c)

**Comment by szyuanyang** [comment]
我直接下载了https://github.com/openimsdk/open-im-server/archive/refs/tags/v3.8.2.tar.gz 部署也是一样的错误，openim-web-front ，openim-admin-front 都登陆不了

**Comment by lgz5689** [comment]
那应该是部署有问题，你可以到 im-server 提一个 issue，先把部署问题解决了先。

**Comment by szyuanyang** [comment]
谢谢，我吧所有的都删除了，chat也删除了重新部署就可以登陆了
