### ISSUE TITLE
unapp中调用删除后数据总量返回改变了

### ISSUE THREAD

**Issue by AirJain** [openimsdk/open-im-uniapp-demo#76]
### What would you like to share?

比如总数据100条 进入消息列表我传的count是20第一次加载返回了20条 然后删除这20条里的某条消息  返回聊天列表后再进入 就只返回19条
DeleteMessage
删除接口
GetAdvancedHistoryMessageList
消息列表接口
请问这是bug吗

**Comment by lgz5689** [comment]
请不要提重复提issue
