### ISSUE TITLE
[BUG] Regarding the problem that many SDKs cannot be used in openim-uniapp-polyfill

### ISSUE THREAD

**Issue by Ru1ers** [openimsdk/open-im-uniapp-demo#77]
### OpenIM Server Version

3.8.2

### Operating System and CPU Architecture

Windows (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

**使用部分sdk时，控制台报错Cannot read properties of undefined (reading 'apply')**
报错位置：
![image](https://github.com/user-attachments/assets/69848e50-f9af-4fa5-8344-e0820f63939e)

情景：在uniapp中使用openim-uniapp-polyfill
测试平台：web
api列表：
**1. 会话相关(未选中都是有问题的)**
- [ ] getAllConversationList
- [x] getConversationListSplit
- [x] getOneConversation
- [ ] getMultipleConversation
- [ ] getConversationIDBySessionType
- [x] getTotalUnreadMsgCount
- [x] markConversationMessageAsRead
- [ ] setConversationDraft
- [x] setConversation
- [ ] hideConversation
- [x] changeInputStates
- [ ] hideAllConversation(此sdk文档中没有具体说明)
- [x] clearConversationAndDeleteAllMsg
- [ ] getInputstates
- [x] deleteConversationAndDeleteAllMsg

### Screenshots Link

**目前只测试了会话相关。
补充说明：部分sdk可以调用成功，所以证明调用方式是没有问题的。
还发现了示例项目中有问题的sdk都没有用到，是否可以理解为这些sdk不支持uniapp，但是文档中uniapp相关确实存在这些sdk。**

**Comment by Ru1ers** [comment]
测试在示例项目中使用上面提到的sdk，也会出现问题。
sdk并没有和文档同步。
是否补充sdk来和文档保持一致。
或者更改文档，去掉不支持的sdk。

**Comment by Bloomingg** [comment]
在新版本jssdk 中部分 api 是没有的，这些在文档上都有标识，如(setConversationDraft)[https://docs.openim.io/zh-Hans/sdks/api/conversation/setConversationDraft],在代码选项卡中并没有写miniProgram。

**Comment by Ru1ers** [comment]
明白了，但是getAllConversationList写了 但是并不支持
![image](https://github.com/user-attachments/assets/77ee2616-0dad-4167-824c-b12d43e06989)
