### ISSUE TITLE
[BUG] setSelfInfo sdk异常

### ISSUE THREAD

**Issue by Ru1ers** [openimsdk/open-im-uniapp-demo#78]
### OpenIM Server Version

3.8.2

### Operating System and CPU Architecture

Windows (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

uniapp，使用setSelfInfo修改当前登录的用户信息时，提示错误：

![image](https://github.com/user-attachments/assets/2bb77e0d-3c0b-47f3-8914-4dff866e3b21)

似乎是说没有传string类型，经过多次排查，传的一定是string
不仅是nickname, faceURL同样存在该问题。

### Screenshots Link

![image](https://github.com/user-attachments/assets/6e495fe6-71df-4c23-a5b0-d870f709c622)
完全按照文档操作
![image](https://github.com/user-attachments/assets/d4b3d8e7-c312-492f-8b36-85d1948010ba)

**Comment by Ru1ers** [comment]
想看下示例项目的，结果示例项目没用sdk，调用的是/user/update接口😭

**Comment by Ru1ers** [comment]
![image](https://github.com/user-attachments/assets/3b2305e1-e79c-4ed3-aef1-557746932f2f)
这个sdk的实际请求把字符串变成对象了

**Comment by lgz5689** [comment]
更新到0.0.10版本
