### ISSUE TITLE
uniapp x Video + conference + voice and other UI interaction implementation plan

### ISSUE THREAD

**Issue by mingyangzhu** [openimsdk/open-im-uniapp-demo#79]
### Why this feature?

uniapp x 视频+会议+语音等ui交互实现计划

### Suggested Solution

uniapp x 视频+会议+语音等ui交互实现 

### Additional Information

随着uniapp 下一代 纯原生的跨平台发布计划，可以考虑这个需求的，后续市场应该不小的。

**Comment by skiffer-git** [comment]
Great suggestion! The project has already started.
